/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/fishing_boat.glb 
Author: JasperTobias (https://sketchfab.com/JasperTobias)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/fishing-boat-e07c8b9cc38543879a4e2fe145e62df6
Title: Fishing Boat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/fishing_boat.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <group position={[0.293, 0.757, 1.876]} scale={0.047}>
          <mesh geometry={nodes.FB_M1_Cabin_Boat_2_0.geometry} material={materials.Boat_2} />
          <mesh geometry={nodes.Lifetorus_Boat_2_0.geometry} material={materials.Boat_2} position={[-6.198, 19.516, -15.467]} rotation={[0.001, Math.PI / 2, 0]} scale={4.376} />
          <mesh geometry={nodes.RadarScanner_Boat_2_0.geometry} material={materials.Boat_2} position={[-6.225, 6.871, 14.109]} scale={21.169} />
          <mesh geometry={nodes.Ladder_Boat_0.geometry} material={materials.Boat} position={[4.356, 9.628, -23.65]} rotation={[0, 0.076, 0]} scale={15.967} />
          <mesh geometry={nodes.Marking_Lights001_Boat_2_0.geometry} material={materials.Boat_2} position={[-6.225, 9.061, -29.645]} scale={21.169} />
        </group>
        <mesh geometry={nodes.FB_Medium_Hull_Boat_2_0.geometry} material={materials.Boat_2} />
        <mesh geometry={nodes.FB_Medium_Hull_Boat_0.geometry} material={materials.Boat} />
        <mesh geometry={nodes.BumpBuoy001_Boat_0.geometry} material={materials.Boat} position={[-0.416, 2.342, 0.975]} rotation={[0, 0, -0.289]} />
        <mesh geometry={nodes.BumpBuoy_Boat_0.geometry} material={materials.Boat} position={[0.674, 1.921, 0.975]} />
        <mesh geometry={nodes.Exhaust_Boat_2_0.geometry} material={materials.Boat_2} position={[0.352, 0.725, 0.481]} rotation={[0, 0.029, 0]} />
        <mesh geometry={nodes.FishHole_Boat_2_0.geometry} material={materials.Boat_2} />
        <mesh geometry={nodes.MastLadder_Boat_2_0.geometry} material={materials.Boat_2} position={[0.882, -1.281, 1.632]} rotation={[-0.072, -0.494, -0.039]} scale={[0.695, 0.615, 0.754]} />
        <mesh geometry={nodes.Lamp_Back_P_Boat_2_0.geometry} material={materials.Boat_2} position={[0.293, 0.758, 1.875]} scale={0.047} />
        <mesh geometry={nodes.Lamp_Back_S_Boat_2_0.geometry} material={materials.Boat_2} position={[-0.424, 0.774, 1.88]} scale={0.047} />
        <mesh geometry={nodes.Lamp_Front_P_Boat_2_0.geometry} material={materials.Boat_2} position={[0.319, -1.236, 2.321]} rotation={[-0.328, 0, 0]} scale={0.049} />
        <mesh geometry={nodes.Lamp_Front_S_Boat_2_0.geometry} material={materials.Boat_2} position={[-0.319, -1.236, 2.321]} rotation={[0.39, 0, -Math.PI]} scale={0.049} />
        <mesh geometry={nodes.Propeller_Boat_2_0.geometry} material={materials.Boat_2} position={[0, 2.502, -0.689]} />
        <mesh geometry={nodes.Rudder_Boat_2_0.geometry} material={materials.Boat_2} position={[0, 2.814, -0.034]} />
      </group>
    </group>
  )
}

useGLTF.preload('/fishing_boat.glb')
