/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/island.glb 
Author: dannzjs (https://sketchfab.com/dannzjs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/island-b0f0f5e8d6c94703892bd3e20596d07e
Title: Island
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/island.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[251.602, 270.29, -664.345]} rotation={[-Math.PI / 2, 0, 1.626]} scale={12.732}>
          <mesh geometry={nodes.Torus_Material030_0.geometry} material={materials['Material.030']} position={[-1.251, 0.011, 0]} rotation={[0, 0, 1.021]} />
        </group>
        <group position={[-33.781, 151.346, 48.618]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane024_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane024_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-49.712, 151.346, 48.618]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane025_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane025_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-66.063, 151.346, 48.618]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane026_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane026_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-83.995, 151.346, 48.618]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane027_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane027_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-108.681, 151.346, 48.618]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane028_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane028_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-138.978, 151.346, 48.618]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane029_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane029_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-125.495, 151.346, 48.618]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane030_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane030_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-97.838, 151.346, 48.618]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane031_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane031_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-22.601, 151.346, 48.618]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane032_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane032_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-33.781, 151.346, 24.655]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane033_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane033_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-49.712, 151.346, 24.655]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane034_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane034_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-66.063, 151.346, 24.655]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane035_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane035_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-83.995, 151.346, 24.655]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane036_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane036_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-108.681, 151.346, 24.655]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane037_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane037_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-138.978, 151.346, 24.655]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane038_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane038_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-125.495, 151.346, 24.655]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane039_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane039_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-97.838, 151.346, 24.655]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane040_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane040_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-22.601, 151.346, 24.655]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane041_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane041_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-33.781, 151.346, 0.611]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane042_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane042_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-49.712, 151.346, 0.611]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane043_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane043_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-66.063, 151.346, 0.611]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane044_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane044_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-83.995, 151.346, 0.611]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane045_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane045_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-108.681, 151.346, 0.611]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane046_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane046_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-138.978, 151.346, 0.611]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane047_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane047_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-125.495, 151.346, 0.611]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane048_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane048_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-97.838, 151.346, 0.611]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane049_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane049_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-22.601, 151.346, 0.611]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane050_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane050_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-33.781, 151.346, -25.046]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane051_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane051_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-49.712, 151.346, -25.046]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane052_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane052_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-66.063, 151.346, -25.046]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane053_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane053_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-83.995, 151.346, -25.046]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane054_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane054_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-108.681, 151.346, -25.046]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane055_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane055_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-138.978, 151.346, -25.046]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane056_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane056_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-125.495, 151.346, -25.046]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane057_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane057_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-97.838, 151.346, -25.046]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane058_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane058_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-22.601, 151.346, -25.046]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane059_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane059_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-33.781, 151.346, -49.26]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane060_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane060_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-49.712, 151.346, -49.26]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane061_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane061_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-66.063, 151.346, -49.26]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane062_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane062_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-83.995, 151.346, -49.26]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane074_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane074_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-108.681, 151.346, -49.26]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane075_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane075_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-138.978, 151.346, -49.26]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane076_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane076_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-125.495, 151.346, -49.26]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane077_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane077_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-97.838, 151.346, -49.26]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane078_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane078_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <group position={[-22.601, 151.346, -49.26]} rotation={[-1.922, 0.676, 1.947]} scale={3.352}>
          <mesh geometry={nodes.Plane079_Material043_0.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Plane079_Material044_0.geometry} material={materials['Material.044']} />
        </group>
        <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder035_Material013_0.geometry} material={materials['Material.013']} position={[-207.414, 162.705, 322.487]} rotation={[-0.05, -1.533, 1.622]} scale={[3.69, 4.554, 22.624]} />
        <mesh geometry={nodes.Circle049_Material021_0.geometry} material={materials['Material.021']} position={[276.293, 182.552, 250.07]} rotation={[-1.572, -0.002, -0.438]} scale={30.834} />
        <mesh geometry={nodes.Cube806_Material021_0.geometry} material={materials['Material.021']} position={[167.537, 156.03, 320.267]} rotation={[-1.572, -0.002, -0.438]} scale={[5.763, 40.738, 1.453]} />
        <mesh geometry={nodes.Cube919_Material021_0.geometry} material={materials['Material.021']} position={[39.616, 182.116, 180.275]} rotation={[2.486, -0.58, -0.399]} scale={[1.457, 1.061, 13.773]} />
        <mesh geometry={nodes.Cube920_Material045_0.geometry} material={materials['Material.045']} position={[34.516, 177.679, 174.041]} rotation={[2.486, -0.58, -0.399]} scale={[1.022, 2.631, 2.863]} />
        <mesh geometry={nodes.Cylinder002_Material046_0.geometry} material={materials['Material.046']} position={[34.91, 162.059, 177.598]} rotation={[-Math.PI / 2, 0, 0.691]} scale={9.227} />
        <mesh geometry={nodes.Cube746_Material008_0.geometry} material={materials['Material.008']} position={[632.053, 65.579, 1282.783]} rotation={[-Math.PI / 2, 0, 0.985]} scale={[1.722, 26.436, 1.722]} />
        <mesh geometry={nodes.Cylinder001_Material021_0.geometry} material={materials['Material.021']} position={[-53.27, 160.719, 210.664]} rotation={[-Math.PI / 2, 0, 0.691]} scale={8.172} />
        <mesh geometry={nodes.Circle_Material062_0.geometry} material={materials['Material.062']} position={[-179.811, 360.497, -709.882]} rotation={[-1.607, -0.014, 2.382]} scale={1.609} />
        <mesh geometry={nodes.Cube790_Material027_0.geometry} material={materials['Material.027']} position={[-146.242, 242.299, 275.689]} rotation={[Math.PI / 2, 0, 0.684]} scale={[-4.172, 4.172, 4.172]} />
        <mesh geometry={nodes.Cube1288_Material027_0.geometry} material={materials['Material.027']} position={[-136.139, 241.409, 186.993]} rotation={[Math.PI / 2, 0, 0.684]} scale={[-4.172, 4.172, 4.172]} />
        <mesh geometry={nodes.Cube1289_Material020_0.geometry} material={materials['Material.020']} position={[23.577, 226.831, -646.355]} rotation={[-1.565, -0.033, -2.708]} scale={6.509} />
        <mesh geometry={nodes.Cube1295_Material019_0.geometry} material={materials['Material.019']} position={[23.577, 226.831, -646.355]} rotation={[-1.565, -0.033, -2.708]} scale={6.509} />
        <mesh geometry={nodes.Cube1296_Material020_0.geometry} material={materials['Material.020']} position={[17.453, 227.505, -667.113]} rotation={[-1.589, 0.004, -2.642]} scale={6.509} />
        <mesh geometry={nodes.Cube1297_Material019_0.geometry} material={materials['Material.019']} position={[17.453, 227.505, -667.113]} rotation={[-1.589, 0.004, -2.642]} scale={6.509} />
        <mesh geometry={nodes.Cube1298_Material020_0.geometry} material={materials['Material.020']} position={[24.983, 240.261, -646.857]} rotation={[-1.565, -0.033, -2.708]} scale={6.509} />
        <mesh geometry={nodes.Cube1299_Material019_0.geometry} material={materials['Material.019']} position={[24.983, 240.261, -646.857]} rotation={[-1.565, -0.033, -2.708]} scale={6.509} />
        <mesh geometry={nodes.Circle063_Material091_0.geometry} material={materials['Material.091']} position={[256.753, 284.731, -699.829]} rotation={[-2.612, 1.141, 2.662]} scale={9.967} />
        <mesh geometry={nodes.Cube1302_Material021_0.geometry} material={materials['Material.021']} position={[249.359, 259.066, -695.375]} rotation={[-1.604, -0.024, 1.947]} scale={[26.504, 20.571, 20.571]} />
        <mesh geometry={nodes.Circle064_Material093_0.geometry} material={materials['Material.093']} position={[254.83, 279.645, -679.938]} rotation={[-0.043, 0.376, 1.596]} scale={[1.838, 1.838, 1.142]} />
        <mesh geometry={nodes.Circle037_Material086_0.geometry} material={materials['Material.086']} position={[203.282, 260.513, -691.854]} rotation={[-Math.PI / 2, 0, 1.626]} scale={20.432} />
        <mesh geometry={nodes.Plane001_Material081_0.geometry} material={materials['Material.081']} position={[199.124, 476.793, -669.746]} rotation={[-1.768, 1.296, 1.776]} scale={[16.868, 18.183, 18.183]} />
        <mesh geometry={nodes.Circle051_Material083_0.geometry} material={materials['Material.083']} position={[51.517, 412.944, -668.964]} rotation={[-Math.PI / 2, 0, 1.626]} scale={44.573} />
        <mesh geometry={nodes.Circle066_Material083_0.geometry} material={materials['Material.083']} position={[51.517, 412.944, -668.964]} rotation={[-Math.PI / 2, 0, -3.082]} scale={44.573} />
        <mesh geometry={nodes.Circle052_Material086_0.geometry} material={materials['Material.086']} position={[195.836, 490.026, -743.019]} rotation={[-0.087, 0.055, 0.005]} scale={20.432} />
        <mesh geometry={nodes.Circle069_Material008_0.geometry} material={materials['Material.008']} position={[199.637, 490.422, -675.345]} rotation={[0, 0.055, -Math.PI / 2]} scale={[-2.906, 3.163, 3.163]} />
        <mesh geometry={nodes.Circle070_Material086_0.geometry} material={materials['Material.086']} position={[203.282, 221.32, -691.854]} rotation={[-Math.PI / 2, 0, 1.626]} scale={20.432} />
        <mesh geometry={nodes.Circle071_Material080_0.geometry} material={materials['Material.080']} position={[203.282, 221.32, -691.854]} rotation={[-Math.PI / 2, 0, 1.626]} scale={20.432} />
        <mesh geometry={nodes.Circle073_Material008_0.geometry} material={materials['Material.008']} position={[194.917, 488.88, -670.464]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[2.736, 3.34, 3.34]} />
        <mesh geometry={nodes._Material008_0.geometry} material={materials['Material.008']} position={[199.575, 490.515, -674.872]} rotation={[0, 0.055, -Math.PI / 2]} scale={[-2.906, 3.163, 3.163]} />
        <mesh geometry={nodes.Circle072_Material008_0.geometry} material={materials['Material.008']} position={[199.517, 490.515, -675.923]} rotation={[0, 0.055, -Math.PI / 2]} scale={[-2.906, 3.163, 3.163]} />
        <mesh geometry={nodes.Circle074_Material008_0.geometry} material={materials['Material.008']} position={[198.383, 490.44, -672.646]} rotation={[0, 0.487, -Math.PI / 2]} scale={[-2.977, 2.977, 2.977]} />
        <mesh geometry={nodes.Circle075__0.geometry} material={materials['Circle.075__0']} position={[187.633, 293.905, -670.753]} rotation={[1.565, -0.112, -1.626]} scale={[-1.896, 1.896, 1.896]} />
        <mesh geometry={nodes.Circle076_Material083_0.geometry} material={materials['Material.083']} position={[170.854, 281.396, -667.136]} rotation={[-Math.PI / 2, 0, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle077_Material083_0.geometry} material={materials['Material.083']} position={[179.708, 281.396, -651.955]} rotation={[-Math.PI / 2, 0, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle078_Material083_0.geometry} material={materials['Material.083']} position={[196.873, 281.396, -647.182]} rotation={[-Math.PI / 2, 0, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle079_Material083_0.geometry} material={materials['Material.083']} position={[213.641, 281.396, -656.932]} rotation={[-Math.PI / 2, 0, -2.265]} scale={2.075} />
        <mesh geometry={nodes.Circle080_Material083_0.geometry} material={materials['Material.083']} position={[217.495, 281.396, -674.078]} rotation={[-Math.PI / 2, 0, -2.265]} scale={2.075} />
        <mesh geometry={nodes.Circle081_Material083_0.geometry} material={materials['Material.083']} position={[208.173, 281.396, -689.263]} rotation={[-Math.PI / 2, 0, -2.265]} scale={2.075} />
        <mesh geometry={nodes.Circle082_Material083_0.geometry} material={materials['Material.083']} position={[190.885, 281.396, -693.725]} rotation={[-Math.PI / 2, 0, -0.705]} scale={2.075} />
        <mesh geometry={nodes.Circle083_Material083_0.geometry} material={materials['Material.083']} position={[175.595, 281.396, -684.578]} rotation={[-Math.PI / 2, 0, -0.705]} scale={2.075} />
        <mesh geometry={nodes.Circle084_Material083_0.geometry} material={materials['Material.083']} position={[90.909, 274.038, -766.455]} rotation={[-Math.PI / 2, 0, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle085_Material083_0.geometry} material={materials['Material.083']} position={[114.759, 274.038, -767.774]} rotation={[-Math.PI / 2, 0, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle086_Material083_0.geometry} material={materials['Material.083']} position={[37.684, 274.038, -763.513]} rotation={[-Math.PI / 2, 0, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle087_Material083_0.geometry} material={materials['Material.083']} position={[61.535, 274.038, -764.831]} rotation={[-Math.PI / 2, 0, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle088_Material083_0.geometry} material={materials['Material.083']} position={[-10.998, 274.038, -760.821]} rotation={[-Math.PI / 2, 0, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle089_Material083_0.geometry} material={materials['Material.083']} position={[12.851, 274.038, -762.139]} rotation={[-Math.PI / 2, 0, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle090_Material083_0.geometry} material={materials['Material.083']} position={[101.04, 275.548, -583.188]} rotation={[-1.57, -0.012, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle091_Material083_0.geometry} material={materials['Material.083']} position={[124.887, 275.839, -584.506]} rotation={[-1.57, -0.012, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle092_Material083_0.geometry} material={materials['Material.083']} position={[47.819, 275.215, -580.245]} rotation={[-1.57, -0.012, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle093_Material083_0.geometry} material={materials['Material.083']} position={[71.667, 275.189, -581.563]} rotation={[-1.57, -0.012, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle094_Material083_0.geometry} material={materials['Material.083']} position={[-0.861, 274.621, -577.553]} rotation={[-1.57, -0.012, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle095_Material083_0.geometry} material={materials['Material.083']} position={[22.987, 274.912, -578.872]} rotation={[-1.57, -0.012, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Plane017_Material094_0.geometry} material={materials['Material.094']} position={[214.816, 580.013, -671.58]} rotation={[0, 0.055, Math.PI / 2]} scale={[5.883, 20.432, 20.432]} />
        <mesh geometry={nodes.Circle096__0.geometry} material={materials['Circle.075__0']} position={[192.146, 500.92, -669.905]} rotation={[-Math.PI / 2, 0, 1.626]} scale={6.865} />
        <mesh geometry={nodes.Plane019_Material028_0.geometry} material={materials['Material.028']} position={[109.318, 258.775, -722.669]} rotation={[-1.606, -0.041, 1.625]} scale={29.543} />
        <mesh geometry={nodes.Cube021_Material019_0.geometry} material={materials['Material.019']} position={[78.118, 255.977, -720.706]} rotation={[-1.606, -0.041, -1.516]} scale={[30.21, 1.061, 2.19]} />
        <mesh geometry={nodes.Plane020_Material028_0.geometry} material={materials['Material.028']} position={[114.773, 260.042, -624.376]} rotation={[-1.566, -0.013, 1.625]} scale={29.543} />
        <mesh geometry={nodes.Cube022_Material019_0.geometry} material={materials['Material.019']} position={[83.533, 258.897, -622.41]} rotation={[-1.562, -0.013, -1.516]} scale={[30.21, 1.061, 2.19]} />
        <mesh geometry={nodes.Cube023_Material090_0.geometry} material={materials['Material.090']} position={[109.337, 250.777, -722.38]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube024_Material089_0.geometry} material={materials['Material.089']} position={[114.833, 248.399, -624.065]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Circle099_Material008_0.geometry} material={materials['Material.008']} position={[12.851, 273.397, -762.139]} rotation={[-Math.PI / 2, 0, 1.032]} scale={2.075} />
        <mesh geometry={nodes.Circle100_Material008_0.geometry} material={materials['Material.008']} position={[12.851, 274.6, -762.139]} rotation={[-Math.PI / 2, 0, 1.032]} scale={2.075} />
        <mesh geometry={nodes.Circle102_Material008_0.geometry} material={materials['Material.008']} position={[61.387, 273.397, -764.823]} rotation={[-Math.PI / 2, 0, 1.027]} scale={2.075} />
        <mesh geometry={nodes.Circle105_Material008_0.geometry} material={materials['Material.008']} position={[114.641, 273.397, -767.767]} rotation={[-Math.PI / 2, 0, 1.27]} scale={2.075} />
        <mesh geometry={nodes.Circle106_Material008_0.geometry} material={materials['Material.008']} position={[114.641, 274.6, -767.767]} rotation={[-Math.PI / 2, 0, 1.27]} scale={2.075} />
        <mesh geometry={nodes.Circle113_Material083_0.geometry} material={materials['Material.083']} position={[6.554, 409.402, -666.557]} rotation={[-2.133, -1.364, -2.143]} scale={1.431} />
        <mesh geometry={nodes.Circle129__0.geometry} material={materials['Circle.075__0']} position={[-192.176, 478.074, -657.361]} rotation={[-Math.PI / 2, 0, 1.626]} scale={5.863} />
        <mesh geometry={nodes.Circle123_Material008_0.geometry} material={materials['Material.008']} position={[194.37, 293.613, -670.535]} rotation={[0, -0.261, -Math.PI / 2]} scale={3.268} />
        <mesh geometry={nodes.Circle124__0.geometry} material={materials['Circle.075__0']} position={[170.888, 284.325, -667.442]} rotation={[Math.PI, 0.184, -Math.PI]} scale={0.411} />
        <mesh geometry={nodes.Circle125__0.geometry} material={materials['Circle.075__0']} position={[-66.917, 339.682, -659.92]} rotation={[-Math.PI / 2, 0, 1.626]} scale={2.075} />
        <mesh geometry={nodes.Circle126__0.geometry} material={materials['Circle.075__0']} position={[-66.606, 339.624, -659.937]} rotation={[-Math.PI / 2, 0, 3.098]} scale={2.075} />
        <mesh geometry={nodes.Circle127__0.geometry} material={materials['Circle.075__0']} position={[-66.606, 339.041, -659.937]} rotation={[-Math.PI / 2, 0, 3.098]} scale={2.075} />
        <mesh geometry={nodes.Circle128__0.geometry} material={materials['Circle.075__0']} position={[-66.606, 340.244, -659.937]} rotation={[-Math.PI / 2, 0, 3.098]} scale={2.075} />
        <mesh geometry={nodes.Cube025_Material036_0.geometry} material={materials['Material.036']} position={[-120.709, 342.994, -663.14]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[45.746, 2.26, 3.831]} />
        <mesh geometry={nodes.Cube026_Material036_0.geometry} material={materials['Material.036']} position={[-1132.897, 152.589, 1213.926]} rotation={[-Math.PI / 2, 0, 1.626]} scale={20.432} />
        <mesh geometry={nodes.Cube027_Material080_0.geometry} material={materials['Material.080']} position={[-120.709, 342.994, -663.14]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[45.746, 2.26, 3.831]} />
        <mesh geometry={nodes.Circle131_Material087_0.geometry} material={materials['Material.087']} position={[-137.295, 386.35, -662.049]} rotation={[Math.PI, 1.516, -Math.PI]} scale={[13.339, 13.339, 16.782]} />
        <mesh geometry={nodes.Circle132_Material088_0.geometry} material={materials['Material.088']} position={[-139.682, 396.763, -674.438]} rotation={[-2.38, -0.04, 1.609]} scale={[20.432, 20.432, 20.278]} />
        <mesh geometry={nodes.Circle145_Material087_0.geometry} material={materials['Material.087']} position={[-139.085, 385.756, -661.975]} rotation={[Math.PI, 1.516, 2.963]} scale={5.297} />
        <mesh geometry={nodes.Cube030_Material025_0.geometry} material={materials['Material.025']} position={[-123.349, 390.244, -710.905]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[45.746, 2.26, 3.831]} />
        <mesh geometry={nodes.Cube031_Material025_0.geometry} material={materials['Material.025']} position={[-118.065, 389.636, -615.328]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[49.775, 2.343, 3.973]} />
        <mesh geometry={nodes.Circle148_Material086_0.geometry} material={materials['Material.086']} position={[198.211, 383.063, -744.592]} rotation={[-0.087, 0.055, 0.005]} scale={20.432} />
        <mesh geometry={nodes.Circle149_Material008_0.geometry} material={materials['Material.008']} position={[202.012, 383.459, -676.918]} rotation={[0, 0.055, -Math.PI / 2]} scale={[-2.906, 3.163, 3.163]} />
        <mesh geometry={nodes.Circle150_Material008_0.geometry} material={materials['Material.008']} position={[196.098, 383.133, -670.625]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[5.129, 6.821, 6.26]} />
        <mesh geometry={nodes.Circle151_Material008_0.geometry} material={materials['Material.008']} position={[201.95, 383.553, -676.445]} rotation={[0, 0.055, -Math.PI / 2]} scale={[-2.906, 3.163, 3.163]} />
        <mesh geometry={nodes.Circle152_Material008_0.geometry} material={materials['Material.008']} position={[201.891, 383.553, -677.497]} rotation={[0, 0.055, -Math.PI / 2]} scale={[-2.906, 3.163, 3.163]} />
        <mesh geometry={nodes.Circle153__0.geometry} material={materials['Circle.075__0']} position={[200.758, 383.478, -674.219]} rotation={[0, 0.487, -Math.PI / 2]} scale={[-2.977, 2.977, 2.977]} />
        <mesh geometry={nodes.Circle156_Material008_0.geometry} material={materials['Material.008']} position={[205.561, 385.149, -573.162]} rotation={[0, 0.487, -Math.PI / 2]} scale={[-2.977, 2.977, 2.977]} />
        <mesh geometry={nodes.Circle157__0.geometry} material={materials['Circle.075__0']} position={[205.501, 385.149, -574.249]} rotation={[0, 0.487, -Math.PI / 2]} scale={[-2.977, 2.977, 2.977]} />
        <mesh geometry={nodes.Circle154_Material008_0.geometry} material={materials['Material.008']} position={[196.111, 381.869, -778.63]} rotation={[0, 0.487, -Math.PI / 2]} scale={[-2.977, 2.977, 2.977]} />
        <mesh geometry={nodes.Circle155_Material008_0.geometry} material={materials['Material.008']} position={[196.051, 381.869, -779.716]} rotation={[0, 0.487, -Math.PI / 2]} scale={[-2.977, 2.977, 2.977]} />
        <mesh geometry={nodes.Circle159_Material008_0.geometry} material={materials['Material.008']} position={[201.177, 491.175, -606.622]} rotation={[0, 0.487, -Math.PI / 2]} scale={[-2.977, 2.977, 2.977]} />
        <mesh geometry={nodes.Circle160_Material008_0.geometry} material={materials['Material.008']} position={[201.117, 491.835, -607.708]} rotation={[0, 0.487, -Math.PI / 2]} scale={[-2.977, 2.977, 2.977]} />
        <mesh geometry={nodes.Circle158_Material008_0.geometry} material={materials['Material.008']} position={[195.699, 488.288, -738.214]} rotation={[0, 0.487, -Math.PI / 2]} scale={[-2.977, 2.977, 2.977]} />
        <mesh geometry={nodes.Circle161_Material008_0.geometry} material={materials['Material.008']} position={[195.64, 488.948, -739.299]} rotation={[0, 0.487, -Math.PI / 2]} scale={[-2.977, 2.977, 2.977]} />
        <mesh geometry={nodes.Cube032_Material079_0.geometry} material={materials['Material.079']} position={[-64.545, 320.025, -668.233]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[6.658, 0.619, 0.619]} />
        <mesh geometry={nodes.Cube033_Material079_0.geometry} material={materials['Material.079']} position={[-69.139, 320.27, -751.319]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[6.658, 0.619, 0.619]} />
        <mesh geometry={nodes.Cube034_Material016_0.geometry} material={materials['Material.016']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube035__0.geometry} material={materials['Circle.075__0']} position={[-66.658, 329.433, -691.527]} rotation={[-Math.PI / 2, 0, 1.626]} scale={1.276} />
        <mesh geometry={nodes.Cube037_Material073_0.geometry} material={materials['Material.073']} position={[-68.604, 253.889, -696.081]} rotation={[-2.04, -0.025, 1.62]} scale={1.584} />
        <mesh geometry={nodes.Circle162__0.geometry} material={materials['Circle.075__0']} position={[-67.541, 284.46, -719.925]} rotation={[Math.PI, 1.516, -Math.PI]} scale={1.188} />
        <mesh geometry={nodes.Cylinder_Material087_0.geometry} material={materials['Material.087']} position={[-132.06, 340.243, -662.346]} rotation={[-Math.PI / 2, 0, 1.626]} scale={1.832} />
        <mesh geometry={nodes.Circle163__0.geometry} material={materials['Circle.075__0']} position={[-132.388, 384.533, -662.658]} rotation={[-Math.PI / 2, 0, 1.626]} scale={20.432} />
        <mesh geometry={nodes.Circle173_Material084_0.geometry} material={materials['Material.084']} position={[-192.169, 340.98, -657.396]} rotation={[-Math.PI / 2, 0, 1.626]} scale={13.087} />
        <mesh geometry={nodes.Cylinder027_Material071_0.geometry} material={materials['Material.071']} position={[-276.294, 277.735, -612.254]} rotation={[-Math.PI / 2, 0, -3.086]} scale={1.399} />
        <mesh geometry={nodes.Cube042__0.geometry} material={materials['Circle.075__0']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube044_Material073_0.geometry} material={materials['Material.073']} position={[-261.96, 287.031, -662.745]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[1.847, 0.816, 1.847]} />
        <mesh geometry={nodes.Circle175__0.geometry} material={materials['Circle.075__0']} position={[52.269, 376.022, -726.195]} rotation={[2.169, 0.133, 3.066]} scale={0.988} />
        <mesh geometry={nodes.Circle174__0.geometry} material={materials['Circle.075__0']} position={[16.821, 376.022, -714.417]} rotation={[2.154, 0, -3.128]} scale={0.988} />
        <mesh geometry={nodes.Circle176__0.geometry} material={materials['Circle.075__0']} position={[92.322, 367.562, -723.003]} rotation={[2.169, 0.133, 3.066]} scale={0.988} />
        <mesh geometry={nodes.Circle177_Material070_0.geometry} material={materials['Material.070']} position={[-260.357, 363.594, -715.707]} rotation={[-Math.PI / 2, 0, 1.626]} scale={7.568} />
        <mesh geometry={nodes.Circle178_Material070_0.geometry} material={materials['Material.070']} position={[-253.836, 363.594, -597.758]} rotation={[-Math.PI / 2, 0, 1.626]} scale={7.568} />
        <mesh geometry={nodes.Cube045_Material015_0.geometry} material={materials['Material.015']} position={[-258.133, 372.676, -696.122]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[2.014, 2.014, 9.557]} />
        <mesh geometry={nodes.Circle179_Material080_0.geometry} material={materials['Material.080']} position={[-258.985, 425.798, -712.206]} rotation={[Math.PI, -0.055, Math.PI / 2]} scale={[20.432, 25.784, 20.432]} />
        <mesh geometry={nodes.Cube046_Material015_0.geometry} material={materials['Material.015']} position={[-172.323, 372.676, -743.026]} rotation={[-Math.PI / 2, 0, 0.282]} scale={[2.014, 2.014, 9.557]} />
        <mesh geometry={nodes.Circle180_Material080_0.geometry} material={materials['Material.080']} position={[-156.844, 425.798, -747.477]} rotation={[-Math.PI, 1.288, Math.PI / 2]} scale={[20.432, 25.784, 20.432]} />
        <mesh geometry={nodes.Cube047_Material015_0.geometry} material={materials['Material.015']} position={[-121.858, 372.676, -757.641]} rotation={[-Math.PI / 2, 0, 0.282]} scale={[2.014, 2.014, 9.557]} />
        <mesh geometry={nodes.Circle181_Material080_0.geometry} material={materials['Material.080']} position={[-121.281, 382.376, -757.883]} rotation={[-Math.PI, 1.288, Math.PI / 2]} scale={[20.432, 25.784, 20.432]} />
        <mesh geometry={nodes.Cube048_Material015_0.geometry} material={materials['Material.015']} position={[-164.338, 372.676, -578.717]} rotation={[-Math.PI / 2, 0, -0.17]} scale={[2.014, 2.014, 9.557]} />
        <mesh geometry={nodes.Circle182_Material080_0.geometry} material={materials['Material.080']} position={[-148.471, 425.798, -575.954]} rotation={[0, 1.401, -Math.PI / 2]} scale={[20.432, 25.784, 20.432]} />
        <mesh geometry={nodes.Cube049_Material015_0.geometry} material={materials['Material.015']} position={[-112.562, 372.676, -569.803]} rotation={[-Math.PI / 2, 0, -0.17]} scale={[2.014, 2.014, 9.557]} />
        <mesh geometry={nodes.Circle183_Material080_0.geometry} material={materials['Material.080']} position={[-111.937, 382.376, -569.767]} rotation={[0, 1.401, -Math.PI / 2]} scale={[20.432, 25.784, 20.432]} />
        <mesh geometry={nodes.Cube050_Material015_0.geometry} material={materials['Material.015']} position={[69.454, 298.339, -568.395]} rotation={[-Math.PI / 2, 0, 0.069]} scale={[2.014, 2.014, 9.557]} />
        <mesh geometry={nodes.Circle184_Material080_0.geometry} material={materials['Material.080']} position={[85.524, 351.461, -569.468]} rotation={[-Math.PI, 1.502, 1.571]} scale={[20.432, 25.784, 20.432]} />
        <mesh geometry={nodes.Circle186_Material084_0.geometry} material={materials['Material.084']} position={[366.119, 280.894, -675.067]} rotation={[-1.681, 1.105, 1.694]} scale={11.172} />
        <mesh geometry={nodes.Circle187_Material008_0.geometry} material={materials['Material.008']} position={[200.822, 383.567, -674.577]} rotation={[0, 0.487, -Math.PI / 2]} scale={[-2.977, 2.977, 2.977]} />
        <mesh geometry={nodes.Circle188_Material008_0.geometry} material={materials['Material.008']} position={[461.876, 329.395, -678.913]} rotation={[-2.403, 0.877, 0.731]} scale={[-3.523, 3.523, 3.523]} />
        <mesh geometry={nodes.Circle189_Material008_0.geometry} material={materials['Material.008']} position={[460.629, 328.334, -678.904]} rotation={[-2.403, 0.877, 0.731]} scale={[-3.523, 3.523, 3.523]} />
        <mesh geometry={nodes.Cube052_Material015_0.geometry} material={materials['Material.015']} position={[57.807, 298.339, -779.037]} rotation={[-Math.PI / 2, 0, 0.048]} scale={[2.014, 2.014, 9.557]} />
        <mesh geometry={nodes.Circle067_Material080_0.geometry} material={materials['Material.080']} position={[73.896, 351.461, -779.768]} rotation={[-Math.PI, 1.523, 1.571]} scale={[20.432, 25.784, 20.432]} />
        <mesh geometry={nodes.Cube053_Material015_0.geometry} material={materials['Material.015']} position={[273.563, 318.835, -616.892]} rotation={[-1.571, -0.105, 0.484]} scale={[2.014, 2.014, 9.557]} />
        <mesh geometry={nodes.Circle190_Material080_0.geometry} material={materials['Material.080']} position={[282.214, 373.158, -624.344]} rotation={[-2.945, 1.077, 1.349]} scale={[20.432, 25.784, 20.432]} />
        <mesh geometry={nodes.Cube055_Material070_0.geometry} material={materials['Material.070']} position={[276.594, 319.154, -618.495]} rotation={[-1.571, -0.105, 0.484]} scale={[2.014, 2.014, 9.557]} />
        <mesh geometry={nodes.Cube056_Material015_0.geometry} material={materials['Material.015']} position={[263.579, 317.822, -740.022]} rotation={[-1.655, -0.051, -0.508]} scale={[2.014, 2.014, 9.557]} />
        <mesh geometry={nodes.Circle191_Material080_0.geometry} material={materials['Material.080']} position={[274.703, 372.085, -736.362]} rotation={[-0.176, 1.061, -1.465]} scale={[20.432, 25.784, 20.432]} />
        <mesh geometry={nodes.Cube057_Material070_0.geometry} material={materials['Material.070']} position={[266.416, 317.746, -737.998]} rotation={[-1.655, -0.051, -0.508]} scale={[2.014, 2.014, 9.557]} />
        <mesh geometry={nodes.Plane014_Material084_0.geometry} material={materials['Material.084']} position={[160.984, 391.152, -722.041]} rotation={[-2.698, -0.172, 1.652]} scale={[122.245, 20.432, 20.432]} />
        <mesh geometry={nodes.Circle193_Material085_0.geometry} material={materials['Material.085']} position={[366.055, 334.059, -676.229]} rotation={[Math.PI, -0.055, Math.PI / 2]} scale={20.432} />
        <mesh geometry={nodes.Cube058_Material080_0.geometry} material={materials['Material.080']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube059_Material071_0.geometry} material={materials['Material.071']} position={[-132.793, 323.703, -755.188]} rotation={[-Math.PI / 2, 0, 1.845]} scale={[1.267, 1.587, 9.51]} />
        <mesh geometry={nodes.Cube038_Material071_0.geometry} material={materials['Material.071']} position={[-131.093, 323.495, -575.824]} rotation={[-1.571, 0.01, 1.416]} scale={[1.267, 1.587, 9.51]} />
        <mesh geometry={nodes.Cube061_Material078_0.geometry} material={materials['Material.078']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Circle185_Material074_0.geometry} material={materials['Material.074']} position={[-263.303, 302.24, -645.485]} rotation={[0, -1.516, 0]} scale={1.099} />
        <mesh geometry={nodes.Circle195_Material008_0.geometry} material={materials['Material.008']} position={[275.074, 264.496, -652.651]} rotation={[-Math.PI / 2, 0, 2.647]} scale={16.19} />
        <mesh geometry={nodes.Cube051_Material030_0.geometry} material={materials['Material.030']} position={[299.232, 237.159, -623.095]} rotation={[-Math.PI / 2, 0, 0.708]} scale={[6.253, 3.845, 7.687]} />
        <mesh geometry={nodes.Cube060_Material020_0.geometry} material={materials['Material.020']} position={[16.457, 227.505, -685.133]} rotation={[-1.589, 0.004, -2.642]} scale={6.509} />
        <mesh geometry={nodes.Cube062_Material019_0.geometry} material={materials['Material.019']} position={[16.457, 227.505, -685.133]} rotation={[-1.589, 0.004, -2.642]} scale={6.509} />
        <mesh geometry={nodes.Cube063_Material020_0.geometry} material={materials['Material.020']} position={[37.093, 227.505, -686.274]} rotation={[-1.589, 0.004, -2.642]} scale={6.509} />
        <mesh geometry={nodes.Cube064_Material019_0.geometry} material={materials['Material.019']} position={[37.093, 227.505, -686.274]} rotation={[-1.589, 0.004, -2.642]} scale={6.509} />
        <mesh geometry={nodes.Cube066_Material020_0.geometry} material={materials['Material.020']} position={[38.189, 227.505, -666.459]} rotation={[-1.589, 0.004, -2.642]} scale={6.509} />
        <mesh geometry={nodes.Cube067_Material019_0.geometry} material={materials['Material.019']} position={[38.189, 227.505, -666.459]} rotation={[-1.589, 0.004, -2.642]} scale={6.509} />
        <mesh geometry={nodes.Cube068_Material020_0.geometry} material={materials['Material.020']} position={[33.465, 243.234, -684.293]} rotation={[-1.589, 0.004, -2.642]} scale={6.509} />
        <mesh geometry={nodes.Cube069_Material019_0.geometry} material={materials['Material.019']} position={[33.465, 243.234, -684.293]} rotation={[-1.589, 0.004, -2.642]} scale={6.509} />
        <mesh geometry={nodes.Cube461__0.geometry} material={materials['Circle.075__0']} position={[2469.307, 403.588, 1398.95]} rotation={[-1.643, -0.038, 0.016]} scale={[0.054, 0.036, 0.182]} />
        <mesh geometry={nodes.Cube510__0.geometry} material={materials['Circle.075__0']} position={[2469.307, 403.588, 1398.95]} rotation={[-1.643, -0.038, 0.016]} scale={[0.224, 0.149, 0.754]} />
        <mesh geometry={nodes.Cube523__0.geometry} material={materials['Circle.075__0']} position={[2469.307, 403.588, 1398.95]} rotation={[-1.643, -0.038, 0.016]} scale={[0.04, 0.027, 0.135]} />
        <mesh geometry={nodes.Cube531__0.geometry} material={materials['Circle.075__0']} position={[2469.307, 403.588, 1398.95]} rotation={[-1.643, -0.038, 0.016]} scale={[0.13, 0.087, 0.439]} />
        <mesh geometry={nodes.Cube547__0.geometry} material={materials['Circle.075__0']} position={[2469.307, 403.588, 1398.95]} rotation={[-1.643, -0.038, 0.016]} scale={[0.043, 0.028, 0.143]} />
        <mesh geometry={nodes.Cube2023_Material095_0.geometry} material={materials['Material.095']} position={[901.769, 27.654, 735.202]} rotation={[-Math.PI / 2, 0.371, 0]} scale={[21.37, 13.338, 13.335]} />
        <mesh geometry={nodes.Circle004_Material092_0.geometry} material={materials['Material.092']} position={[876.117, 37.861, 735.202]} rotation={[Math.PI / 2, 1.2, -Math.PI]} scale={[15.232, 15.236, 19.195]} />
        <mesh geometry={nodes.Cube3292_Material017_0.geometry} material={materials['Material.017']} position={[99.824, 111.708, -206.211]} rotation={[-1.418, -0.003, 0.064]} scale={[6.82, 6.797, 4.355]} />
        <mesh geometry={nodes.Cube3293_Material016_0.geometry} material={materials['Material.016']} position={[99.824, 111.708, -206.211]} rotation={[-1.418, -0.003, 0.064]} scale={[5.203, 5.185, 3.322]} />
        <mesh geometry={nodes.Cube3294_Material015_0.geometry} material={materials['Material.015']} position={[99.824, 111.708, -206.211]} rotation={[-1.418, -0.003, 0.064]} scale={[6.82, 6.797, 4.355]} />
        <mesh geometry={nodes.Vert022_Material008_0.geometry} material={materials['Material.008']} position={[117.074, 150.986, -269.159]} rotation={[-1.378, 0.016, -1.012]} scale={[31.118, 40.417, 25.866]} />
        <mesh geometry={nodes.Cube3295_Material096_0.geometry} material={materials['Material.096']} position={[903.471, 33.223, 720.193]} rotation={[-Math.PI / 2, 0.376, 0]} scale={[1.55, 0.651, 2.241]} />
        <mesh geometry={nodes.Cube3296_Material017_0.geometry} material={materials['Material.017']} position={[-814.486, 48.309, 973.558]} rotation={[-1.565, 0.025, 2.503]} scale={3.436} />
        <mesh geometry={nodes.Cube3297_Material016_0.geometry} material={materials['Material.016']} position={[-814.486, 48.309, 973.558]} rotation={[-1.565, 0.025, 2.503]} scale={2.621} />
        <mesh geometry={nodes.Cube3298_Material015_0.geometry} material={materials['Material.015']} position={[-814.486, 48.309, 973.558]} rotation={[-1.565, 0.025, 2.503]} scale={3.436} />
        <mesh geometry={nodes.Vert032_Material015_0.geometry} material={materials['Material.015']} position={[-822.81, 78.26, 970.701]} rotation={[-1.512, 0.025, 1.427]} scale={[15.673, 20.432, 20.432]} />
        <mesh geometry={nodes.Cube001_Material072_0.geometry} material={materials['Material.072']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube002_Material003_0.geometry} material={materials['Material.003']} position={[0, -11.356, 167.617]} rotation={[-Math.PI / 2, 0, 0]} scale={[1250, 1250, 49.984]} />
        <mesh geometry={nodes.Cube004_Material004_0.geometry} material={materials['Material.004']} position={[0, -0.348, 167.617]} rotation={[-Math.PI / 2, 0, 0]} scale={[1250, 1250, 50]} />
        <mesh geometry={nodes.Cube005_Material005_0.geometry} material={materials['Material.005']} position={[0, -9.222, 147.777]} rotation={[-Math.PI / 2, 0, 0]} scale={[682.395, 682.395, 6.823]} />
        <mesh geometry={nodes.Cube006_Material008_0.geometry} material={materials['Material.008']} position={[386.82, 99.945, 861.643]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.685, 4.048, 29.563]} />
        <mesh geometry={nodes.BezierCurve_Material008_0.geometry} material={materials['Material.008']} position={[489.968, 71.899, 1080.886]} rotation={[-Math.PI / 2, 0, -1.406]} scale={96.282} />
        <mesh geometry={nodes.Cylinder031_Material021_0.geometry} material={materials['Material.021']} position={[293.769, 162.881, 466.067]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.791, 3.791, 55.186]} />
        <mesh geometry={nodes.Circle005_Material002_0.geometry} material={materials['Material.002']} position={[293.769, 218.19, 466.067]} rotation={[-Math.PI / 2, 0, 0]} scale={47.593} />
        <mesh geometry={nodes.Cube072_Material008_0.geometry} material={materials['Material.008']} position={[616.211, 65.579, 1300.201]} rotation={[-Math.PI / 2, 0, 0.705]} scale={[1.722, 26.436, 1.722]} />
        <mesh geometry={nodes.Vert044_Material018_0.geometry} material={materials['Material.018']} position={[52.94, 123.558, -666.386]} rotation={[-Math.PI / 2, 0, 1.626]} scale={100} />
        <mesh geometry={nodes.Plane071_Material007_0.geometry} material={materials['Material.007']} position={[164.158, 117.078, 646.627]} rotation={[-1.922, 0.676, 1.947]} scale={18.906} />
        <mesh geometry={nodes.Plane013_Material007_0.geometry} material={materials['Material.007']} position={[323.162, 95.481, 617.62]} rotation={[-1.922, 0.676, 1.947]} scale={18.884} />
        <mesh geometry={nodes.Plane015_Material007_0.geometry} material={materials['Material.007']} position={[323.162, 120.926, -124.501]} rotation={[-1.922, 0.676, 1.947]} scale={31.029} />
        <mesh geometry={nodes.Cube003_Material042_0.geometry} material={materials['Material.042']} position={[-84.255, 142.071, -1.052]} rotation={[-Math.PI / 2, 0, 0]} scale={[67.87, 67.87, 7.517]} />
        <mesh geometry={nodes.Cube010_Material008_0.geometry} material={materials['Material.008']} position={[-155.406, 138.829, -150.391]} rotation={[-Math.PI / 2, 0, 0.286]} scale={[3.454, 6.298, 37.378]} />
        <mesh geometry={nodes.Cube015_Material006_0.geometry} material={materials['Material.006']} position={[567.19, 105.659, 262.196]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-74.175, 36.337, 0.602]} />
        <mesh geometry={nodes.Cube036_Material064_0.geometry} material={materials['Material.064']} position={[57.288, 216.6, -532.841]} rotation={[-Math.PI / 2, 0, 0]} scale={[13.62, 10.161, 3.443]} />
        <mesh geometry={nodes.Cube074_Material063_0.geometry} material={materials['Material.063']} position={[63.288, 234.529, -523.102]} rotation={[Math.PI / 2, 0, -0.231]} scale={[-3.908, 0.509, 0.509]} />
        <mesh geometry={nodes.Cube075_Material063_0.geometry} material={materials['Material.063']} position={[51.891, 234.529, -523.102]} rotation={[Math.PI / 2, 0, 0.23]} scale={[-3.908, 0.509, 0.509]} />
        <mesh geometry={nodes.Sphere009_Material065_0.geometry} material={materials['Material.065']} position={[62.892, 231.831, -522.388]} rotation={[Math.PI / 2, 0, 0]} scale={[-1.229, 1.229, 1.229]} />
        <mesh geometry={nodes.Sphere011_Material065_0.geometry} material={materials['Material.065']} position={[51.339, 231.831, -522.549]} rotation={[Math.PI / 2, 0, 0]} scale={[-1.229, 1.229, 1.229]} />
        <mesh geometry={nodes.Cube076_Material063_0.geometry} material={materials['Material.063']} position={[57.176, 222.789, -519.041]} rotation={[-Math.PI / 2, 0, 0]} scale={0.777} />
        <mesh geometry={nodes.Cube077_Material060_0.geometry} material={materials['Material.060']} position={[57.288, 216.6, -532.841]} rotation={[-Math.PI / 2, 0, 0]} scale={[13.62, 10.161, 3.443]} />
        <mesh geometry={nodes.Cube078_Material008_0.geometry} material={materials['Material.008']} position={[154.572, 179.411, 166.331]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.945, 4.945, 35.036]} />
        <mesh geometry={nodes.Cube079_Material047_0.geometry} material={materials['Material.047']} position={[154.572, 150.321, 129.378]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.371, 25.869, 41.585]} />
        <mesh geometry={nodes.Cylinder003_Material013_0.geometry} material={materials['Material.013']} position={[964.269, 25.232, 129.378]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.716, 10.716, 62.476]} />
        <mesh geometry={nodes.Cylinder005_Material014_0.geometry} material={materials['Material.014']} position={[964.269, 38.625, 129.378]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.716, 10.716, 62.476]} />
        <mesh geometry={nodes.Cube080_Material008_0.geometry} material={materials['Material.008']} position={[-933.202, 76.045, 1159.408]} rotation={[-Math.PI / 2, 0, 0.985]} scale={[1.722, 26.436, 1.722]} />
        <mesh geometry={nodes.Cube081_Material008_0.geometry} material={materials['Material.008']} position={[-949.043, 76.045, 1176.827]} rotation={[-Math.PI / 2, 0, 0.705]} scale={[1.722, 26.436, 1.722]} />
        <mesh geometry={nodes.Plane016_Material007_0.geometry} material={materials['Material.007']} position={[477.364, 97.384, -124.501]} rotation={[-1.922, 0.676, 1.947]} scale={15.173} />
        <mesh geometry={nodes.Plane022_Material007_0.geometry} material={materials['Material.007']} position={[477.364, 98.778, 48.331]} rotation={[-1.922, 0.676, 1.947]} scale={17.34} />
        <mesh geometry={nodes.Cube086_Material008_0.geometry} material={materials['Material.008']} position={[726.469, 72.809, 283.332]} rotation={[-0.753, -1.386, 0.895]} scale={[3.454, 6.298, 37.378]} />
        <mesh geometry={nodes.Cylinder010_Material056_0.geometry} material={materials['Material.056']} position={[950.142, 118.319, -686.703]} rotation={[-Math.PI / 2, 0, 0.295]} scale={138.154} />
        <mesh geometry={nodes.Sphere014__0.geometry} material={materials['Circle.075__0']} position={[950.168, 763.36, -686.805]} rotation={[-Math.PI / 2, 0, -0.864]} scale={4.126} />
        <mesh geometry={nodes.Cylinder011_Material028_0.geometry} material={materials['Material.028']} position={[950.142, 118.319, -686.703]} rotation={[-Math.PI / 2, 0, 0.295]} scale={138.154} />
        <mesh geometry={nodes.Cylinder013_Material027_0.geometry} material={materials['Material.027']} position={[950.142, 118.319, -686.703]} rotation={[-Math.PI / 2, 0, 0.295]} scale={138.154} />
        <mesh geometry={nodes.Cylinder023_Material047_0.geometry} material={materials['Material.047']} position={[950.142, 118.319, -686.703]} rotation={[-Math.PI / 2, 0, 0.295]} scale={138.154} />
        <mesh geometry={nodes.Cylinder024_Material054_0.geometry} material={materials['Material.054']} position={[950.142, 129.678, -686.703]} rotation={[-Math.PI / 2, 0, 0.295]} scale={134.713} />
        <mesh geometry={nodes.Cylinder025_Material051_0.geometry} material={materials['Material.051']} position={[1054.311, 533.985, -699.316]} rotation={[-Math.PI / 2, 0, 0.295]} scale={138.154} />
        <mesh geometry={nodes.Cube087_Material053_0.geometry} material={materials['Material.053']} position={[975.205, 546.445, -604.096]} rotation={[-Math.PI / 2, 0, 0.295]} scale={[7.783, 1.922, 3.672]} />
        <mesh geometry={nodes.Cube088_Material049_0.geometry} material={materials['Material.049']} position={[945.142, 193.634, -667.03]} rotation={[-Math.PI / 2, 0, 1.158]} scale={[157.533, 157.533, 4.999]} />
        <mesh geometry={nodes.Cube089_Material048_0.geometry} material={materials['Material.048']} position={[945.142, 193.634, -667.03]} rotation={[-Math.PI / 2, 0, 1.158]} scale={[154.45, 154.45, 4.901]} />
        <mesh geometry={nodes.Cube091_Material048_0.geometry} material={materials['Material.048']} position={[1007.369, 263.747, -808.734]} rotation={[-Math.PI / 2, 0, 1.158]} scale={[4.03, 149.738, 3.561]} />
        <mesh geometry={nodes.Cube092_Material057_0.geometry} material={materials['Material.057']} position={[851.85, 231.493, -505.636]} rotation={[-1.25, -0.137, 1.18]} scale={[6.591, 3.776, 2.482]} />
        <mesh geometry={nodes.Cylinder036__0.geometry} material={materials['Circle.075__0']} position={[945.142, 74.548, -667.03]} rotation={[-Math.PI / 2, 0, 0]} scale={115.607} />
        <mesh geometry={nodes.Cube114_Material009_0.geometry} material={materials['Material.009']} position={[1002.753, 91.618, -545.024]} rotation={[-0.758, 0.631, 0.463]} scale={[-95.535, 42.227, 42.227]} />
        <mesh geometry={nodes.Cube119_Material009_0.geometry} material={materials['Material.009']} position={[1026.34, 135.796, -774.267]} rotation={[2.622, 0.307, -2.532]} scale={[-88.657, 39.186, 39.186]} />
        <mesh geometry={nodes.Cube122_Material057_0.geometry} material={materials['Material.057']} position={[802.396, 177.538, -377.55]} rotation={[-1.181, -0.152, 1.108]} scale={[6.591, 3.776, 2.482]} />
        <mesh geometry={nodes.Cylinder040_Material010_0.geometry} material={materials['Material.010']} position={[273.419, -50.167, 667.061]} rotation={[-Math.PI / 2, 0, -0.256]} scale={[22.231, 22.231, 19.244]} />
        <mesh geometry={nodes.Plane063_Material011_0.geometry} material={materials['Material.011']} position={[-233.69, 86.571, 1097.823]} rotation={[-0.86, 0.259, 0.137]} scale={37.341} />
        <mesh geometry={nodes.Plane064_Material007_0.geometry} material={materials['Material.007']} position={[-158.528, 117.078, 646.627]} rotation={[-1.922, 0.676, 1.947]} scale={18.906} />
        <mesh geometry={nodes.Plane065_Material007_0.geometry} material={materials['Material.007']} position={[-52.213, 117.078, 577.062]} rotation={[-1.922, 0.676, 1.947]} scale={18.906} />
        <mesh geometry={nodes.Plane066_Material007_0.geometry} material={materials['Material.007']} position={[-266.101, 100.827, 617.805]} rotation={[-1.922, 0.676, 1.947]} scale={18.906} />
        <mesh geometry={nodes.Plane067_Material007_0.geometry} material={materials['Material.007']} position={[-235.19, 99.361, 730.22]} rotation={[-1.922, 0.676, 1.947]} scale={18.906} />
        <mesh geometry={nodes.Sphere023_Material009_0.geometry} material={materials['Material.009']} position={[567.135, 82.131, 141.598]} rotation={[-Math.PI / 2, 0, 0]} scale={[6.511, 9.007, 2.418]} />
        <mesh geometry={nodes.Sphere024_Material009_0.geometry} material={materials['Material.009']} position={[1138.363, -10.99, 761.286]} rotation={[-Math.PI / 2, 0, 0]} scale={[44.137, 142.858, 38.354]} />
        <mesh geometry={nodes.Sphere025_Material012_0.geometry} material={materials['Material.012']} position={[515.518, 89.926, 207.919]} rotation={[Math.PI / 2, 0, 0]} scale={[13.798, 19.379, 8.651]} />
        <mesh geometry={nodes.Cylinder041__0.geometry} material={materials['Circle.075__0']} position={[527.757, 92.766, 204.074]} rotation={[-Math.PI / 2, 1.066, 0]} scale={1.055} />
        <mesh geometry={nodes.Cube012_Material018_0.geometry} material={materials['Material.018']} position={[-565.285, 79.62, 689.068]} rotation={[-Math.PI / 2, 0, 0]} scale={[128.483, 106.156, 11.578]} />
        <mesh geometry={nodes.Cylinder043_Material013_0.geometry} material={materials['Material.013']} position={[-394.237, 91.483, 796.796]} rotation={[-0.05, -1.533, 1.622]} scale={[3.69, 4.554, 22.624]} />
        <mesh geometry={nodes.Cube013_Material020_0.geometry} material={materials['Material.020']} position={[-593.982, 17.051, 682.717]} rotation={[-1.589, 0.004, -2.642]} scale={17.084} />
        <mesh geometry={nodes.Cube014_Material019_0.geometry} material={materials['Material.019']} position={[-593.982, 17.051, 682.717]} rotation={[-1.589, 0.004, -2.642]} scale={17.084} />
        <mesh geometry={nodes.Cube043_Material020_0.geometry} material={materials['Material.020']} position={[-493.449, 13.672, 702.973]} rotation={[-1.565, -0.033, -2.708]} scale={17.084} />
        <mesh geometry={nodes.Cube065_Material019_0.geometry} material={materials['Material.019']} position={[-493.449, 13.672, 702.973]} rotation={[-1.565, -0.033, -2.708]} scale={17.084} />
        <mesh geometry={nodes.Cube070_Material020_0.geometry} material={materials['Material.020']} position={[-537.525, 17.051, 664.697]} rotation={[-1.589, 0.004, -2.642]} scale={17.084} />
        <mesh geometry={nodes.Cube071_Material019_0.geometry} material={materials['Material.019']} position={[-537.525, 17.051, 664.697]} rotation={[-1.589, 0.004, -2.642]} scale={17.084} />
        <mesh geometry={nodes.Plane068_Material007_0.geometry} material={materials['Material.007']} position={[333.165, 134.987, 48.331]} rotation={[-1.922, 0.676, 1.947]} scale={17.34} />
        <mesh geometry={nodes.Plane069_Material007_0.geometry} material={materials['Material.007']} position={[222.957, 134.987, -60.275]} rotation={[-1.922, 0.676, 1.947]} scale={17.34} />
        <mesh geometry={nodes.Plane070_Material007_0.geometry} material={materials['Material.007']} position={[173.093, 134.987, -60.275]} rotation={[-1.922, 0.676, 1.947]} scale={17.34} />
        <mesh geometry={nodes.Plane072_Material007_0.geometry} material={materials['Material.007']} position={[201.228, 147.492, 79.717]} rotation={[-1.922, 0.676, 1.947]} scale={17.34} />
        <mesh geometry={nodes.Sphere026_Material022_0.geometry} material={materials['Material.022']} position={[227.775, 95.232, 604.918]} rotation={[-Math.PI / 2, 0, 0]} scale={12.914} />
        <mesh geometry={nodes.Sphere027_Material022_0.geometry} material={materials['Material.022']} position={[214.814, 112.204, 562.622]} rotation={[-Math.PI / 2, 0, 0]} scale={12.914} />
        <mesh geometry={nodes.Sphere028_Material022_0.geometry} material={materials['Material.022']} position={[53.868, 114.53, 541.004]} rotation={[-Math.PI / 2, 0, 0]} scale={12.914} />
        <mesh geometry={nodes.Sphere030_Material009_0.geometry} material={materials['Material.009']} position={[406.919, 104.647, 312.195]} rotation={[-Math.PI / 2, 0, 0]} scale={[22.994, 72.098, 11.457]} />
        <mesh geometry={nodes.Sphere031_Material009_0.geometry} material={materials['Material.009']} position={[-277.545, 93.219, -249.529]} rotation={[-1.694, 0, 0]} scale={[22.994, 72.098, 11.457]} />
        <mesh geometry={nodes.Cube093__0.geometry} material={materials['Circle.075__0']} position={[1033.609, -41.668, 900.993]} rotation={[2.622, 0.307, -2.532]} scale={[-88.657, 39.186, 39.186]} />
        <mesh geometry={nodes.Plane073_Material023_0.geometry} material={materials['Material.023']} position={[0, -109.669, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={5765.265} />
        <mesh geometry={nodes.Cylinder008_Material010_0.geometry} material={materials['Material.010']} position={[246.526, -39.611, 223.533]} rotation={[-Math.PI / 2, 0, -0.808]} scale={[25.07, 25.07, 21.702]} />
        <mesh geometry={nodes.Plane007_Material011_0.geometry} material={materials['Material.011']} position={[-495.187, 114.595, 337.181]} rotation={[-0.829, -0.112, -0.275]} scale={42.111} />
        <mesh geometry={nodes.Cylinder009_Material010_0.geometry} material={materials['Material.010']} position={[-82.106, -50.167, 577.758]} rotation={[-Math.PI / 2, 0, -0.256]} scale={[22.231, 22.231, 19.244]} />
        <mesh geometry={nodes.Plane008_Material011_0.geometry} material={materials['Material.011']} position={[-589.215, 86.571, 1008.519]} rotation={[-0.86, 0.259, 0.137]} scale={37.341} />
        <mesh geometry={nodes.Cylinder029_Material010_0.geometry} material={materials['Material.010']} position={[-108.999, -80.921, -285.271]} rotation={[-1.456, 0, -0.808]} scale={[25.07, 25.07, 21.702]} />
        <mesh geometry={nodes.Plane010_Material011_0.geometry} material={materials['Material.011']} position={[-850.712, 59.249, -154.705]} rotation={[-0.714, -0.112, -0.275]} scale={42.111} />
        <mesh geometry={nodes.Cylinder030_Material010_0.geometry} material={materials['Material.010']} position={[-478.372, -97.807, 62.323]} rotation={[-1.456, 0, -0.808]} scale={[28.721, 28.721, 24.862]} />
        <mesh geometry={nodes.Plane011_Material011_0.geometry} material={materials['Material.011']} position={[-1328.073, 62.771, 211.899]} rotation={[-0.714, -0.112, -0.275]} scale={48.242} />
        <mesh geometry={nodes.Cylinder032_Material010_0.geometry} material={materials['Material.010']} position={[-478.372, -97.807, 387.238]} rotation={[-1.456, 0, -0.808]} scale={[28.721, 28.721, 24.862]} />
        <mesh geometry={nodes.Plane012_Material011_0.geometry} material={materials['Material.011']} position={[-1328.073, 62.771, 536.814]} rotation={[-0.714, -0.112, -0.275]} scale={48.242} />
        <mesh geometry={nodes.Sphere032_Material022_0.geometry} material={materials['Material.022']} position={[-37.003, 134.369, 433.041]} rotation={[-Math.PI / 2, 0, 0]} scale={12.914} />
        <mesh geometry={nodes.Sphere033_Material022_0.geometry} material={materials['Material.022']} position={[-63.104, 134.369, 433.041]} rotation={[-Math.PI / 2, 0, 0]} scale={12.914} />
        <mesh geometry={nodes.Sphere034_Material022_0.geometry} material={materials['Material.022']} position={[-63.104, 134.369, 457.656]} rotation={[-Math.PI / 2, 0, 0]} scale={12.914} />
        <mesh geometry={nodes.Sphere035_Material022_0.geometry} material={materials['Material.022']} position={[-38.068, 134.369, 457.656]} rotation={[-Math.PI / 2, 0, 0]} scale={12.914} />
        <mesh geometry={nodes.Sphere036_Material022_0.geometry} material={materials['Material.022']} position={[-54.913, 147.524, 446.891]} rotation={[-Math.PI / 2, 0, 0]} scale={12.914} />
        <mesh geometry={nodes.Plane023_Material007_0.geometry} material={materials['Material.007']} position={[-117.234, 140.278, 445.892]} rotation={[-1.922, 0.676, 1.947]} scale={18.906} />
        <mesh geometry={nodes.Cylinder033_Material052_0.geometry} material={materials['Material.052']} position={[950.142, 118.319, -686.703]} rotation={[-Math.PI / 2, 0, 0.295]} scale={138.154} />
        <mesh geometry={nodes.Cylinder006_Material055_0.geometry} material={materials['Material.055']} position={[950.142, 118.319, -686.703]} rotation={[-Math.PI / 2, 0, 0.295]} scale={138.154} />
        <mesh geometry={nodes.Cube008_Material049_0.geometry} material={materials['Material.049']} position={[945.142, 193.634, -667.03]} rotation={[-Math.PI / 2, 0, 1.158]} scale={[157.533, 157.533, 4.999]} />
        <mesh geometry={nodes.Cube094_Material049_0.geometry} material={materials['Material.049']} position={[945.142, 193.634, -667.03]} rotation={[-Math.PI / 2, 0, 1.158]} scale={[157.533, 157.533, 4.999]} />
        <mesh geometry={nodes.Vert001_Material015_0.geometry} material={materials['Material.015']} position={[52.94, 123.558, -666.386]} rotation={[-Math.PI / 2, 0, 1.626]} scale={100} />
        <mesh geometry={nodes.Cube095_Material059_0.geometry} material={materials['Material.059']} position={[57.288, 216.6, -532.841]} rotation={[-Math.PI / 2, 0, 0]} scale={[13.62, 10.161, 3.443]} />
        <mesh geometry={nodes.Cube096_Material064_0.geometry} material={materials['Material.064']} position={[57.288, 216.6, -532.841]} rotation={[-Math.PI / 2, 0, 0]} scale={[13.62, 10.161, 3.443]} />
        <mesh geometry={nodes.Cube097_Material066_0.geometry} material={materials['Material.066']} position={[57.288, 216.6, -532.841]} rotation={[-Math.PI / 2, 0, 0]} scale={[13.62, 10.161, 3.443]} />
        <mesh geometry={nodes.Cube105_Material061_0.geometry} material={materials['Material.061']} position={[57.288, 216.6, -532.841]} rotation={[-Math.PI / 2, 0, 0]} scale={[13.62, 10.161, 3.443]} />
        <mesh geometry={nodes.Cube106_Material067_0.geometry} material={materials['Material.067']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube107__0.geometry} material={materials['Circle.075__0']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube108_Material068_0.geometry} material={materials['Material.068']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube109_Material077_0.geometry} material={materials['Material.077']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube110__0.geometry} material={materials['Circle.075__0']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube111_Material069_0.geometry} material={materials['Material.069']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube016_Material071_0.geometry} material={materials['Material.071']} position={[-132.793, 323.703, -755.188]} rotation={[-Math.PI / 2, 0, 1.845]} scale={[1.267, 1.587, 9.51]} />
        <mesh geometry={nodes.Cube019_Material069_0.geometry} material={materials['Material.069']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube039_Material069_0.geometry} material={materials['Material.069']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Cube040_Material027_0.geometry} material={materials['Material.027']} position={[35.297, 269.374, -672.309]} rotation={[-Math.PI / 2, 0, 1.626]} scale={[70.548, 234.836, 20.432]} />
        <mesh geometry={nodes.Sphere038_Material009_0.geometry} material={materials['Material.009']} position={[953.341, -10.99, 1056.505]} rotation={[-1.892, 0.277, -0.281]} scale={[44.137, 119.627, 38.354]} />
        <mesh geometry={nodes.Circle003_Material025_0.geometry} material={materials['Material.025']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Circle007_Material029_0.geometry} material={materials['Material.029']} position={[-61.745, 143.908, 799.365]} rotation={[-Math.PI / 2, 0, 0.355]} scale={20.432} />
        <mesh geometry={nodes.Circle009_Material038_0.geometry} material={materials['Material.038']} position={[-127.789, 314.51, 234.101]} rotation={[-Math.PI / 2, 0, 0.355]} scale={3.055} />
        <mesh geometry={nodes.Circle011_Material039_0.geometry} material={materials['Material.039']} position={[-131.323, 302.15, 231.903]} rotation={[-1.449, 0.186, 2.556]} scale={0.341} />
        <mesh geometry={nodes.Cube749_Material035_0.geometry} material={materials['Material.035']} position={[-126.82, 303.244, 236.008]} rotation={[-Math.PI / 2, 0, 0.355]} scale={20.432} />
        <mesh geometry={nodes.Circle018_Material036_0.geometry} material={materials['Material.036']} position={[-120.337, 304.055, 247.015]} rotation={[-Math.PI / 2, 0, 0.355]} scale={[0.917, 0.847, 1.351]} />
        <mesh geometry={nodes.Plane002_Material026_0.geometry} material={materials['Material.026']} position={[-148.455, 234.208, 274.465]} rotation={[-Math.PI / 2, 0, 1.186]} scale={10.986} />
        <mesh geometry={nodes.Cube751_Material041_0.geometry} material={materials['Material.041']} position={[-132.633, 303.238, 223.582]} rotation={[-Math.PI / 2, 0, 1.036]} scale={0.357} />
        <mesh geometry={nodes.Cube752_Material040_0.geometry} material={materials['Material.040']} position={[-144.65, 318.821, 227.027]} rotation={[-Math.PI / 2, 0, 1.036]} scale={[3.866, 0.168, 3.049]} />
        <mesh geometry={nodes.Circle019__0.geometry} material={materials['Circle.075__0']} position={[-130.025, 315.617, 232.753]} rotation={[-Math.PI, 1.216, Math.PI]} scale={0.06} />
        <mesh geometry={nodes.Plane003_Material025_0.geometry} material={materials['Material.025']} position={[-136.588, 233.947, 187.283]} rotation={[-Math.PI / 2, 0, 1.905]} scale={10.986} />
        <mesh geometry={nodes.Circle020_Material033_0.geometry} material={materials['Material.033']} position={[-136.207, 356.497, 207.628]} rotation={[-Math.PI / 2, 0, 0.229]} scale={20.432} />
        <mesh geometry={nodes.Cube756__0.geometry} material={materials['Circle.075__0']} position={[-136.339, 351.605, 207.498]} rotation={[-Math.PI / 2, 0, 0.229]} scale={0.208} />
        <mesh geometry={nodes.Plane004__0.geometry} material={materials['Circle.075__0']} position={[-130.994, 339.629, 205.349]} rotation={[-Math.PI / 2, 0, 0.258]} scale={2.403} />
        <mesh geometry={nodes.Circle021_Material033_0.geometry} material={materials['Material.033']} position={[-143.42, 356.638, 259.991]} rotation={[-Math.PI / 2, 0, -0.621]} scale={20.432} />
        <mesh geometry={nodes.Cube757__0.geometry} material={materials['Circle.075__0']} position={[-143.319, 351.747, 260.002]} rotation={[-Math.PI / 2, 0, -0.621]} scale={0.208} />
        <mesh geometry={nodes.Plane005__0.geometry} material={materials['Circle.075__0']} position={[-138.266, 339.77, 262.401]} rotation={[-Math.PI / 2, 0, -0.591]} scale={2.403} />
        <mesh geometry={nodes.Circle022_Material037_0.geometry} material={materials['Material.037']} position={[-122.474, 317.929, 237.018]} rotation={[-0.252, 1.029, 0.372]} scale={2.554} />
        <mesh geometry={nodes.Cylinder004__0.geometry} material={materials['Circle.075__0']} position={[78.837, 266.193, -609.979]} rotation={[-Math.PI / 2, 0, 0.691]} scale={4.167} />
        <mesh geometry={nodes.Cylinder007__0.geometry} material={materials['Circle.075__0']} position={[-55.368, 163.016, 218.731]} rotation={[0, -0.444, Math.PI / 2]} scale={0.814} />
        <mesh geometry={nodes.Cube763_Material024_0.geometry} material={materials['Material.024']} position={[-39.199, 161.674, 201.422]} rotation={[-Math.PI / 2, 0, 0.691]} scale={0.516} />
        <mesh geometry={nodes.Plane009_Material028_0.geometry} material={materials['Material.028']} position={[-155.494, 210.689, 232.945]} rotation={[0, 1.431, -1.571]} scale={[21.779, 29.655, 43.842]} />
        <mesh geometry={nodes.Sphere_Material081_0.geometry} material={materials['Material.081']} position={[51.138, 698.266, -670.52]} rotation={[-1.587, -0.001, -2.802]} scale={123.532} />
        <mesh geometry={nodes.Sphere001_Material008_0.geometry} material={materials['Material.008']} position={[50.816, 698.265, -670.447]} rotation={[-1.585, 0.007, 2.981]} scale={123.532} />
        <mesh geometry={nodes.Cube792_Material076_0.geometry} material={materials['Material.076']} position={[-254.592, 179.704, -654.514]} rotation={[-1.561, -0.217, 1.594]} scale={[3.9, 3.875, 3.351]} />
        <mesh geometry={nodes.Circle029_Material083_0.geometry} material={materials['Material.083']} position={[49.832, 512.96, -667.498]} rotation={[-1.587, -0.001, -2.802]} scale={20.432} />
        <mesh geometry={nodes.Circle030_Material008_0.geometry} material={materials['Material.008']} position={[49.832, 512.96, -667.498]} rotation={[-1.587, -0.001, -2.802]} scale={20.432} />
        <mesh geometry={nodes.Sphere002_Material008_0.geometry} material={materials['Material.008']} position={[50.707, 698.266, -670.465]} rotation={[-1.585, 0.007, 2.981]} scale={123.532} />
        <mesh geometry={nodes.Sphere003_Material008_0.geometry} material={materials['Material.008']} position={[50.826, 741.893, -672.255]} rotation={[-1.585, 0.007, 2.981]} scale={109.687} />
        <mesh geometry={nodes.Sphere004_Material008_0.geometry} material={materials['Material.008']} position={[50.707, 698.266, -670.465]} rotation={[-1.585, 0.007, 2.981]} scale={123.532} />
        <mesh geometry={nodes.Circle038_Material038_0.geometry} material={materials['Material.038']} position={[-90.567, 380.833, -737.526]} rotation={[-1.567, 0.031, 1.045]} scale={10.427} />
        <mesh geometry={nodes.Circle040_Material038_0.geometry} material={materials['Material.038']} position={[-105.946, 339.097, -735.78]} rotation={[-1.594, 0.251, -3.022]} scale={1.162} />
        <mesh geometry={nodes.Circle042__0.geometry} material={materials['Circle.075__0']} position={[-99.261, 384.879, -736.203]} rotation={[3.127, 0.526, -3.106]} scale={0.205} />
        <mesh geometry={nodes.Circle043_Material037_0.geometry} material={materials['Material.037']} position={[-69.886, 391.882, -741.356]} rotation={[-2.589, 1.382, 2.76]} scale={8.717} />
        <mesh geometry={nodes.Cube800_Material008_0.geometry} material={materials['Material.008']} position={[-273.264, 156.026, 12.008]} rotation={[-0.914, -0.793, 1.052]} scale={20.432} />
        <mesh geometry={nodes.Cube801_Material008_0.geometry} material={materials['Material.008']} position={[624.18, 58.207, 1284.593]} rotation={[-1.515, -0.068, 0.693]} scale={20.432} />
        <mesh geometry={nodes.Cube803_Material008_0.geometry} material={materials['Material.008']} position={[603.227, 63.427, 1258.884]} rotation={[1.592, 0.026, 2.45]} scale={[-24.68, 3.381, 1.1]} />
        <mesh geometry={nodes.Cube804_Material008_0.geometry} material={materials['Material.008']} position={[644.104, 63.427, 1308.329]} rotation={[1.592, 0.026, 2.45]} scale={[-24.02, 3.291, 1.071]} />
        <mesh geometry={nodes.Circle046_Material031_0.geometry} material={materials['Material.031']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Circle047_Material031_0.geometry} material={materials['Material.031']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Sphere005_Material008_0.geometry} material={materials['Material.008']} position={[50.707, 698.266, -670.465]} rotation={[-1.585, 0.007, 1.797]} scale={123.532} />
        <mesh geometry={nodes.Sphere006_Material008_0.geometry} material={materials['Material.008']} position={[50.707, 698.266, -670.465]} rotation={[-1.585, 0.007, 0.596]} scale={123.532} />
        <mesh geometry={nodes.Sphere007_Material008_0.geometry} material={materials['Material.008']} position={[50.707, 698.266, -670.465]} rotation={[-1.585, 0.007, -0.569]} scale={123.532} />
        <mesh geometry={nodes.Sphere008_Material008_0.geometry} material={materials['Material.008']} position={[50.707, 698.266, -670.465]} rotation={[-1.585, 0.007, -2.129]} scale={123.532} />
        <mesh geometry={nodes.Circle058_Material032_0.geometry} material={materials['Material.032']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Circle059_Material034_0.geometry} material={materials['Material.034']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Circle014_Material050_0.geometry} material={materials['Material.050']} position={[-136.207, 356.497, 207.628]} rotation={[-Math.PI / 2, 0, 0.229]} scale={20.432} />
        <mesh geometry={nodes.Circle015_Material027_0.geometry} material={materials['Material.027']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Circle016_Material027_0.geometry} material={materials['Material.027']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Circle017_Material058_0.geometry} material={materials['Material.058']} position={[-61.745, 143.908, 799.365]} rotation={[-Math.PI / 2, 0, 0.355]} scale={20.432} />
        <mesh geometry={nodes.Circle060_Material027_0.geometry} material={materials['Material.027']} position={[-61.745, 143.908, 799.365]} rotation={[-Math.PI / 2, 0, 0.355]} scale={20.432} />
        <mesh geometry={nodes.Circle061_Material027_0.geometry} material={materials['Material.027']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Circle062_Material034_0.geometry} material={materials['Material.034']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Cube1300_Material075_0.geometry} material={materials['Material.075']} position={[-254.592, 179.704, -654.514]} rotation={[-1.561, -0.217, 1.594]} scale={[3.9, 3.875, 3.351]} />
        <mesh geometry={nodes.Cube018_Material016_0.geometry} material={materials['Material.016']} position={[-10.106, 258.678, -569.807]} rotation={[1.562, 0.058, 1.442]} scale={[-16.569, 4.219, 1.091]} />
        <mesh geometry={nodes.Cube017_Material017_0.geometry} material={materials['Material.017']} position={[-3.184, 210.048, -650.577]} rotation={[-3.126, 0.012, 0.987]} scale={[-16.569, 4.219, 1.091]} />
        <mesh geometry={nodes.Sphere010_Material008_0.geometry} material={materials['Material.008']} position={[152.315, 316.275, -665.687]} rotation={[-1.534, -0.366, -0.151]} scale={65.279} />
        <mesh geometry={nodes.Sphere012_Material008_0.geometry} material={materials['Material.008']} position={[64.995, 328.695, -749.007]} rotation={[-1.59, 0.035, 1.468]} scale={65.279} />
        <mesh geometry={nodes.Sphere013_Material008_0.geometry} material={materials['Material.008']} position={[-7.138, 395.874, -660.794]} rotation={[-1.681, 0.802, 3.073]} scale={65.279} />
        <mesh geometry={nodes.Sphere015_Material008_0.geometry} material={materials['Material.008']} position={[23.433, 357.698, -619.554]} rotation={[-1.552, -0.035, -1.674]} scale={65.279} />
        <mesh geometry={nodes.Sphere016_Material008_0.geometry} material={materials['Material.008']} position={[15.91, 328.484, -745.756]} rotation={[-1.59, 0.035, 1.468]} scale={65.279} />
        <mesh geometry={nodes.Sphere018_Material008_0.geometry} material={materials['Material.008']} position={[49.938, 613.946, -670.376]} rotation={[-1.585, 0.007, 2.981]} scale={109.687} />
        <mesh geometry={nodes.Sphere019_Material008_0.geometry} material={materials['Material.008']} position={[132.604, 533.444, -663.783]} rotation={[-1.587, 0.541, -0.16]} scale={123.532} />
        <mesh geometry={nodes.Sphere020_Material008_0.geometry} material={materials['Material.008']} position={[59.835, 513.098, -602.579]} rotation={[-1.039, 0.104, -1.589]} scale={123.532} />
        <mesh geometry={nodes.Sphere021_Material008_0.geometry} material={materials['Material.008']} position={[-34.516, 510.004, -669.241]} rotation={[-1.596, -0.101, -0.088]} scale={123.532} />
        <mesh geometry={nodes.Sphere022_Material008_0.geometry} material={materials['Material.008']} position={[43.59, 514.55, -754.237]} rotation={[-1.675, 0.007, -1.483]} scale={123.532} />
        <mesh geometry={nodes.Circle097__0.geometry} material={materials['Circle.075__0']} position={[-54.464, 318.145, -592.324]} rotation={[-Math.PI / 2, 0, 0.024]} scale={20.432} />
        <mesh geometry={nodes.Cube020__0.geometry} material={materials['Circle.075__0']} position={[-54.377, 313.253, -592.377]} rotation={[-Math.PI / 2, 0, 0.024]} scale={0.208} />
        <mesh geometry={nodes.Plane018__0.geometry} material={materials['Circle.075__0']} position={[-48.895, 301.277, -593.496]} rotation={[-Math.PI / 2, 0, 0.054]} scale={2.403} />
        <mesh geometry={nodes.Sphere029__0.geometry} material={materials['Circle.075__0']} position={[-146.089, 518.144, -656.937]} rotation={[-1.681, 0.802, 3.073]} scale={50.052} />
        <mesh geometry={nodes.Cube082_Material008_0.geometry} material={materials['Material.008']} position={[-941.074, 68.673, 1161.219]} rotation={[-1.515, -0.068, 0.693]} scale={20.432} />
        <mesh geometry={nodes.Cube083_Material008_0.geometry} material={materials['Material.008']} position={[-962.027, 73.893, 1135.51]} rotation={[1.592, 0.026, 2.45]} scale={[-24.68, 3.381, 1.1]} />
        <mesh geometry={nodes.Cube084_Material008_0.geometry} material={materials['Material.008']} position={[-921.151, 73.893, 1184.955]} rotation={[1.592, 0.026, 2.45]} scale={[-24.02, 3.291, 1.071]} />
        <mesh geometry={nodes.Cube085_Material008_0.geometry} material={materials['Material.008']} position={[777.658, 60.051, 602.315]} rotation={[-Math.PI / 2, 0.434, 0.691]} scale={[20.432, 82.235, 9.305]} />
        <mesh geometry={nodes.Circle001_Material021_0.geometry} material={materials['Material.021']} position={[35.734, 140.697, 424.935]} rotation={[-1.572, 0.032, -2.776]} scale={15.432} />
        <mesh geometry={nodes.Circle006_Material024_0.geometry} material={materials['Material.024']} position={[35.734, 140.697, 424.935]} rotation={[-1.572, 0.032, -2.776]} scale={15.432} />
        <mesh geometry={nodes.Circle008_Material021_0.geometry} material={materials['Material.021']} position={[38.987, 148.236, 384.622]} rotation={[-1.572, 0.032, -2.776]} scale={15.432} />
        <mesh geometry={nodes.Circle023_Material024_0.geometry} material={materials['Material.024']} position={[38.987, 148.236, 384.622]} rotation={[-1.572, 0.032, -2.776]} scale={15.432} />
        <mesh geometry={nodes.Circle024_Material025_0.geometry} material={materials['Material.025']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Circle025_Material025_0.geometry} material={materials['Material.025']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Circle026_Material025_0.geometry} material={materials['Material.025']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Circle027_Material025_0.geometry} material={materials['Material.025']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Circle031_Material050_0.geometry} material={materials['Material.050']} position={[-143.42, 356.638, 259.991]} rotation={[-Math.PI / 2, 0, -0.621]} scale={20.432} />
        <mesh geometry={nodes.Circle032_Material029_0.geometry} material={materials['Material.029']} position={[-210.327, 144.588, 224.06]} rotation={[-Math.PI / 2, 0, 0.355]} scale={83.325} />
        <mesh geometry={nodes.Sphere037_Material008_0.geometry} material={materials['Material.008']} position={[91.054, 328.695, -749.007]} rotation={[-1.59, 0.035, 1.468]} scale={65.279} />
        <mesh geometry={nodes.Circle010_Material021_0.geometry} material={materials['Material.021']} position={[217.334, 257.155, -630.436]} rotation={[-1.572, 0.032, -2.776]} scale={15.432} />
        <mesh geometry={nodes.Circle012_Material024_0.geometry} material={materials['Material.024']} position={[217.334, 257.155, -630.436]} rotation={[-1.572, 0.032, -2.776]} scale={15.432} />
        <mesh geometry={nodes.Circle028_Material021_0.geometry} material={materials['Material.021']} position={[203.251, 254.173, -659.42]} rotation={[-1.572, 0.032, -2.776]} scale={15.432} />
        <mesh geometry={nodes.Circle033_Material024_0.geometry} material={materials['Material.024']} position={[203.251, 254.173, -659.42]} rotation={[-1.572, 0.032, -2.776]} scale={15.432} />
        <mesh geometry={nodes.Circle034_Material021_0.geometry} material={materials['Material.021']} position={[208.608, 259.981, -583.707]} rotation={[-1.572, 0.032, -2.776]} scale={6.537} />
        <mesh geometry={nodes.Circle035_Material024_0.geometry} material={materials['Material.024']} position={[208.608, 259.981, -583.707]} rotation={[-1.572, 0.032, -2.776]} scale={6.537} />
        <mesh geometry={nodes.Circle036_Material021_0.geometry} material={materials['Material.021']} position={[200.533, 259.464, -565.553]} rotation={[-1.572, 0.032, -2.776]} scale={6.537} />
        <mesh geometry={nodes.Circle039_Material024_0.geometry} material={materials['Material.024']} position={[200.533, 259.464, -565.553]} rotation={[-1.572, 0.032, -2.776]} scale={6.537} />
        <mesh geometry={nodes.Circle041_Material021_0.geometry} material={materials['Material.021']} position={[198.207, 259.299, -576.232]} rotation={[-1.572, 0.032, -2.776]} scale={6.537} />
        <mesh geometry={nodes.Circle044_Material024_0.geometry} material={materials['Material.024']} position={[198.207, 259.299, -576.232]} rotation={[-1.572, 0.032, -2.776]} scale={6.537} />
        <mesh geometry={nodes.Circle002_Material082_0.geometry} material={materials['Material.082']} position={[-186.672, 349.866, -714.371]} rotation={[-1.607, -0.014, 2.084]} scale={2.186} />
      </group>
    </group>
  )
}

useGLTF.preload('/island.glb')
