/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/kauai_island_hawaii_-_pacific_ocean.glb 
Author: Nate Loper   🗺️ ⛏🏺  #ArizonaGuide (https://sketchfab.com/arizonaguide)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kauai-island-hawaii-pacific-ocean-a108514634fe439b9bade0456bfd5bd8
Title: Kauai Island, Hawaii - Pacific Ocean
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kauai_island_hawaii_-_pacific_ocean.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials['rastMat.006']} position={[-45788.672, -34649.5, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/kauai_island_hawaii_-_pacific_ocean.glb')
