/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/lighthouse_-_handpainted.glb 
Author: gozdemrl (https://sketchfab.com/gozdemrl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lighthouse-handpainted-4af03930d5cc4251ad7228fc6b436c20
Title: Lighthouse - Handpainted
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lighthouse_-_handpainted.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[335.068, 2114.007, 120.131]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder002_sea_light_up_0.geometry} material={materials.sea_light_up} />
          <mesh geometry={nodes.Cylinder002_sea_light_glass_0.geometry} material={materials.sea_light_glass} />
        </group>
        <group position={[386.434, 843.608, 659.004]} rotation={[-Math.PI / 2, 0, 0.514]} scale={100}>
          <mesh geometry={nodes.Cube023_Window_base_0.geometry} material={materials.Window_base} />
          <mesh geometry={nodes.Cube023_glass_1_0.geometry} material={materials.glass_1} />
        </group>
        <mesh geometry={nodes.Cube_ground_0.geometry} material={materials.ground} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder006_Wood_2_0.geometry} material={materials.Wood_2} position={[-755.73, 325.262, 682.236]} rotation={[-1.382, -0.121, 0.009]} scale={100} />
        <mesh geometry={nodes.Cube009_Wood_1_0.geometry} material={materials.Wood_1} position={[814.549, 551.699, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Cylinder_sea_light_0.geometry} material={materials.sea_light} position={[370.413, 594.261, 120.131]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube001_base_build_0.geometry} material={materials.base_build} position={[340.662, 663.787, -273.375]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube004_wood_wall_2_0.geometry} material={materials.wood_wall_2} position={[340.662, 663.787, 512.729]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube014__0.geometry} material={materials['Cube.014__0']} position={[154.604, 705.991, -273.375]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 66.698]} />
        <mesh geometry={nodes.Cube008_wood_wall_0.geometry} material={materials.wood_wall} position={[-131.562, 943.415, 508.48]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder001_sea_light_korkuluk_0.geometry} material={materials.sea_light_korkuluk} position={[370.413, 692.291, 120.131]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder003_sea_light_door_0.geometry} material={materials.sea_light_door} position={[332.709, 1469.317, -13.589]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube010_roof_1_0.geometry} material={materials.roof_1} position={[395.048, 995.305, 119.91]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube012_Roof_wood_0.geometry} material={materials.Roof_wood} position={[821.771, 955.03, 118.006]} rotation={[-Math.PI / 2, 0.971, 0]} scale={100} />
        <mesh geometry={nodes.Cube015_base_door_0.geometry} material={materials.base_door} position={[23.681, 750.122, 316.755]} rotation={[-Math.PI / 2, 0, 0]} scale={96.774} />
        <mesh geometry={nodes.Cylinder004_pervane_0.geometry} material={materials.pervane} position={[703.625, 1086.022, -258.111]} rotation={[-1.566, 0.349, -0.005]} scale={100} />
        <mesh geometry={nodes.Plane_shark_0.geometry} material={materials.shark} position={[52.351, 1380.398, 519.257]} rotation={[Math.PI, -0.119, 2.787]} scale={100} />
        <mesh geometry={nodes.Cylinder005_direk_1_0.geometry} material={materials.direk_1} position={[-50.686, 993.493, 600.672]} rotation={[-Math.PI / 2, -0.099, 0]} scale={100} />
        <mesh geometry={nodes.Torus_cankurtaran_0.geometry} material={materials.cankurtaran} position={[-38.327, 735.138, -53.15]} rotation={[-Math.PI / 2, 1.366, 0]} scale={[64.957, 64.957, 49.211]} />
        <mesh geometry={nodes.Cylinder008_posta_0.geometry} material={materials.posta} position={[-916.108, 715.274, 119.49]} rotation={[-Math.PI / 2, -0.466, 0]} scale={100} />
        <mesh geometry={nodes.Cube021_stairs_0.geometry} material={materials.stairs} position={[-913.483, 277.312, 401.04]} rotation={[-1.531, Math.PI / 2, 0]} scale={100} />
        <mesh geometry={nodes.Plane001_tekne_0.geometry} material={materials.tekne} position={[233.054, 363.901, -848.629]} rotation={[-Math.PI / 2, 0.026, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder009_krek_0.geometry} material={materials.krek} position={[284.349, 429.477, -706.74]} rotation={[-2.208, 0.306, 2.755]} scale={100} />
        <mesh geometry={nodes.Cylinder011_varil_0.geometry} material={materials.varil} position={[387.434, 602.021, -454.475]} rotation={[-Math.PI / 2, 0, -0.49]} scale={100} />
        <mesh geometry={nodes.Cylinder012_can_0.geometry} material={materials.material} position={[565.279, 908.003, -612.724]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Torus001_top_0.geometry} material={materials.material_25} position={[-742.498, 404.394, -188.23]} rotation={[-2.539, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder017_rook_0.geometry} material={materials.rook} position={[370.413, 594.261, 120.131]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.NurbsPath006_Rope_0.geometry} material={materials.Rope} position={[-803.041, 304.242, -142.532]} rotation={[0, -0.496, -Math.PI / 2]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/lighthouse_-_handpainted.glb')
