/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/xyz_homework_detailed_draft_fishermans_house.glb 
Author: merryminder (https://sketchfab.com/merryminder)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/xyz-homework-detailed-draft-fishermans-house-8dd23310590142689fbaed441d54dc4b
Title: XYZ Homework: detailed draft fisherman's house
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/xyz_homework_detailed_draft_fishermans_house.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 201.51, 0]} scale={[0.96, 1.028, 0.96]}>
        <mesh geometry={nodes.Cube_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube_Material012_0.geometry} material={materials['Material.012']} />
      </group>
      <group position={[0, 201.51, 0]} scale={[1, 1.071, 1]}>
        <mesh geometry={nodes.Cube002_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube002_Material006_0.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-29.886, 158.139, 136.419]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube008_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube008_Material006_0.geometry} material={materials['Material.006']} />
      </group>
      <group position={[183.552, 120.71, 18.217]}>
        <mesh geometry={nodes.Cylinder_Material006_0.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder_Material008_0.geometry} material={materials['Material.008']} />
      </group>
      <group position={[74.789, 114.081, 223.446]} scale={[0.24, 1, 1]}>
        <mesh geometry={nodes.Cube013_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube013_Material009_0.geometry} material={materials['Material.009']} />
      </group>
      <group position={[74.789, 114.081, 239.478]} rotation={[0, Math.PI / 2, 0]} scale={[0.24, 1, 1.05]}>
        <mesh geometry={nodes.Cube014_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube014_Material009_0.geometry} material={materials['Material.009']} />
      </group>
      <group position={[15.984, 120.71, 250.616]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cylinder003_Material006_0.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder003_Material008_0.geometry} material={materials['Material.008']} />
      </group>
      <group position={[74.789, 115.771, 163.433]} rotation={[1.003, 0, 0]} scale={[0.116, 1, 0.553]}>
        <mesh geometry={nodes.Cube015_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube015_Material009_0.geometry} material={materials['Material.009']} />
      </group>
      <group position={[-13.273, 230.399, 108.515]} scale={[0.581, 0.222, 0.448]}>
        <mesh geometry={nodes.Cube018_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube018_Material007_0.geometry} material={materials['Material.007']} />
      </group>
      <group position={[0, 301.26, 58.514]} scale={[1, 1.071, 1]}>
        <mesh geometry={nodes.Cube019_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube019_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube019_Material012_0.geometry} material={materials['Material.012']} />
      </group>
      <group position={[-7.566, 341.175, 41.932]} scale={[1.385, 1.071, 1]}>
        <mesh geometry={nodes.Cube020_Material010_0.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube020_Material005_0.geometry} material={materials['Material.005']} />
      </group>
      <group position={[0, 300.472, 0]} scale={[1, 1.071, 1]}>
        <mesh geometry={nodes.Cube023_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube023_Material005_0.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-26.363, 248.64, 139.035]} rotation={[Math.PI / 2, -0.365, 0]} scale={[0.567, 0.567, 0.142]}>
        <mesh geometry={nodes.Plane_Material013_0.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Plane_Material016_0.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Plane_Material002_0.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Cube001_Material005_0.geometry} material={materials['Material.005']} position={[0, -57.047, 0]} />
      <mesh geometry={nodes.Cube003_Material009_0.geometry} material={materials['Material.009']} position={[0, 199.11, 0]} scale={[1.088, 1, 1.088]} />
      <mesh geometry={nodes.Cube004_Material011_0.geometry} material={materials['Material.011']} position={[0, 197.224, 0]} />
      <mesh geometry={nodes.Cube005_Material009_0.geometry} material={materials['Material.009']} position={[-17.624, 201.51, 0]} scale={[1, 1.071, 1]} />
      <mesh geometry={nodes.Cube006_Material005_0.geometry} material={materials['Material.005']} position={[-0.184, 201.51, 69.159]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1.071, 1.2]} />
      <mesh geometry={nodes.Cube007_Material005_0.geometry} material={materials['Material.005']} position={[-13.089, 201.51, 135.533]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1.071, 1]} />
      <mesh geometry={nodes.Cube009_Material005_0.geometry} material={materials['Material.005']} position={[-29.886, 173.559, 136.419]} rotation={[0, Math.PI / 2, 0]} scale={[1, 0.253, 1]} />
      <mesh geometry={nodes.Cube011_Material005_0.geometry} material={materials['Material.005']} position={[-101.746, 173.559, 61.706]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 0.253, 1]} />
      <mesh geometry={nodes.Cylinder001_Material006_0.geometry} material={materials['Material.006']} position={[-94.744, 120.71, 18.217]} />
      <mesh geometry={nodes.Cylinder002_Material009_0.geometry} material={materials['Material.009']} position={[88, 180, 0]} />
      <mesh geometry={nodes.Cube012_Material009_0.geometry} material={materials['Material.009']} position={[86.892, 179.353, 1.496]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1.071, 1]} />
      <mesh geometry={nodes.Cylinder004_Material006_0.geometry} material={materials['Material.006']} position={[74.733, 120.71, 135.035]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cylinder005_Material006_0.geometry} material={materials['Material.006']} position={[98.777, 146.58, 0.402]} scale={[0.583, 0.6, 0.583]} />
      <mesh geometry={nodes.Cylinder006_Material006_0.geometry} material={materials['Material.006']} position={[117.103, 146.58, -0.575]} scale={[0.583, 0.6, 0.583]} />
      <mesh geometry={nodes.Cylinder007_Material005_0.geometry} material={materials['Material.005']} position={[15.043, 266.352, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[3.755, 2.035, 1.553]} />
      <mesh geometry={nodes.Cube016_Material007_0.geometry} material={materials['Material.007']} position={[0, 284.775, 0]} scale={[1.02, 1.071, 1.127]} />
      <mesh geometry={nodes.Cube017_Material009_0.geometry} material={materials['Material.009']} position={[-10.669, 229.268, 107.385]} rotation={[0.31, 0, 0]} scale={[0.391, 1, 0.391]} />
      <mesh geometry={nodes.Cube021_Material005_0.geometry} material={materials['Material.005']} position={[90.602, 276.164, 0]} />
      <mesh geometry={nodes.Cube022_Material005_0.geometry} material={materials['Material.005']} position={[-89.626, 278.517, 0]} rotation={[0, 0, -0.126]} scale={[1.002, 1.1, 1]} />
      <mesh geometry={nodes.Cube024_Material005_0.geometry} material={materials['Material.005']} position={[155.448, 314.612, 0]} />
      <mesh geometry={nodes.Cube025_Material015_0.geometry} material={materials['Material.015']} position={[128.821, 77.722, 0]} rotation={[0, 0, 0.455]} scale={[1, 1.105, 1]} />
      <mesh geometry={nodes.Cube026_Material005_0.geometry} material={materials['Material.005']} position={[207.844, 145.024, 1.496]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1.071, 1]} />
      <mesh geometry={nodes.Cylinder008_Material006_0.geometry} material={materials['Material.006']} position={[179.894, 120.71, 79.779]} />
      <mesh geometry={nodes.Cube027_Material009_0.geometry} material={materials['Material.009']} position={[-8.111, 297.902, 59.467]} />
      <mesh geometry={nodes.Cube028_Material009_0.geometry} material={materials['Material.009']} position={[-8.111, 335.313, 20.131]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.068, 1, 1]} />
      <mesh geometry={nodes.Cube058_Material006_0.geometry} material={materials['Material.006']} position={[14.882, 131.079, 240.584]} scale={[1, 1.071, 1]} />
      <mesh geometry={nodes.Cube059_Material006_0.geometry} material={materials['Material.006']} position={[72.754, 131.079, 170.868]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1.071, 1.06]} />
      <mesh geometry={nodes.Cube060_Material009_0.geometry} material={materials['Material.009']} position={[-80.864, 201.51, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1.071, 1]} />
      <mesh geometry={nodes.Cube061_Material009_0.geometry} material={materials['Material.009']} position={[-87.462, 179.353, 1.496]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1.071, 1]} />
      <mesh geometry={nodes.Cube062_Material005_0.geometry} material={materials['Material.005']} position={[193.826, -57.047, 0]} />
      <mesh geometry={nodes.Cylinder018_Material001_0.geometry} material={materials['Material.001']} position={[-79.409, 209.62, -0.772]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder019_Material001_0.geometry} material={materials['Material.001']} position={[-79.409, 209.62, 7.561]} rotation={[0.085, 0, 0]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder020_Material001_0.geometry} material={materials['Material.001']} position={[-79.409, 209.62, -10.254]} rotation={[-0.111, 0, 0]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder021_Material001_0.geometry} material={materials['Material.001']} position={[-79.395, 203.033, -1.348]} rotation={[1.456, 0, 0]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder022_Material001_0.geometry} material={materials['Material.001']} position={[-79.395, 197.556, -1.348]} rotation={[1.632, 0, 0]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder023_Material001_0.geometry} material={materials['Material.001']} position={[-79.395, 212.514, -1.348]} rotation={[1.523, 0, 0]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder024_Material001_0.geometry} material={materials['Material.001']} position={[76.912, 206.312, -0.772]} scale={[0.268, 0.62, 0.268]} />
      <mesh geometry={nodes.Cylinder025_Material001_0.geometry} material={materials['Material.001']} position={[76.912, 206.312, 7.561]} rotation={[0.149, 0, 0]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder026_Material001_0.geometry} material={materials['Material.001']} position={[76.912, 206.312, -10.254]} rotation={[-0.072, 0, 0]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder027_Material001_0.geometry} material={materials['Material.001']} position={[76.927, 199.726, -1.348]} rotation={[1.605, 0, 0]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder028_Material001_0.geometry} material={materials['Material.001']} position={[76.927, 194.248, -1.348]} rotation={[1.61, 0, 0]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder029_Material001_0.geometry} material={materials['Material.001']} position={[76.927, 209.207, -1.348]} rotation={[1.519, 0, 0]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cube064_Material005_0.geometry} material={materials['Material.005']} position={[-29.886, 173.559, -96.285]} rotation={[0, Math.PI / 2, 0]} scale={[1, 0.253, 1]} />
      <mesh geometry={nodes.Cube065_Material006_0.geometry} material={materials['Material.006']} position={[0, 162.079, 77.892]} scale={[1.088, 1.016, 1.088]} />
      <mesh geometry={nodes.Cube067_Material006_0.geometry} material={materials['Material.006']} position={[-0.84, 172.743, 65.18]} rotation={[0, Math.PI / 2, 0]} scale={[0.539, 0.136, 0.439]} />
      <mesh geometry={nodes.Cube068_Material006_0.geometry} material={materials['Material.006']} position={[-23.283, 206.136, 64.056]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.539, 0.136, 0.439]} />
      <mesh geometry={nodes.Cube010_Material008_0.geometry} material={materials['Material.008']} position={[-13.069, 224.516, 137.31]} rotation={[0.308, Math.PI / 2, 0]} scale={[1, 1.071, 1.06]} />
      <mesh geometry={nodes.Cube063_Material005_0.geometry} material={materials['Material.005']} position={[-58.701, 274.859, 64.903]} rotation={[-0.443, 0, 0]} scale={[1, 0.756, 1]} />
      <mesh geometry={nodes.Cube066_Material010_0.geometry} material={materials['Material.010']} position={[-13.799, 295.226, -55.121]} />
      <mesh geometry={nodes.Cube069_Material005_0.geometry} material={materials['Material.005']} position={[119.083, 306.499, -20.468]} rotation={[0.752, -0.321, 0.04]} />
      <mesh geometry={nodes.Cube070_Material005_0.geometry} material={materials['Material.005']} position={[-35.59, 294.636, -51.73]} rotation={[0.199, 0, 0]} />
      <mesh geometry={nodes.Cube071_Material009_0.geometry} material={materials['Material.009']} position={[6.406, 308.838, -35.277]} rotation={[0.309, 0.059, -0.019]} />
      <mesh geometry={nodes.Cube072_Material005_0.geometry} material={materials['Material.005']} position={[-20.74, 260.088, -74.016]} rotation={[-0.213, -0.081, 0.241]} />
      <mesh geometry={nodes.Cube073_Material005_0.geometry} material={materials['Material.005']} position={[-0.184, 201.51, -66.853]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1.071, 1.2]} />
      <mesh geometry={nodes.Cube074_Material009_0.geometry} material={materials['Material.009']} position={[1.672, 182.044, -63.452]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 1.071, 1]} />
      <mesh geometry={nodes.Cube075_Material009_0.geometry} material={materials['Material.009']} position={[1.672, 228.614, -63.452]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 1.071, 1]} />
      <mesh geometry={nodes.Cylinder030_Material001_0.geometry} material={materials['Material.001']} position={[0.081, 206.312, -61.807]} rotation={[0, Math.PI / 2, 0]} scale={[0.268, 0.62, 0.268]} />
      <mesh geometry={nodes.Cylinder031_Material001_0.geometry} material={materials['Material.001']} position={[8.415, 206.312, -61.807]} rotation={[Math.PI / 2, 1.425, -Math.PI / 2]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder032_Material001_0.geometry} material={materials['Material.001']} position={[-9.4, 206.312, -61.807]} rotation={[-Math.PI / 2, 1.441, Math.PI / 2]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder033_Material001_0.geometry} material={materials['Material.001']} position={[-0.495, 199.726, -61.822]} rotation={[Math.PI / 2, 0.024, -Math.PI / 2]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder034_Material001_0.geometry} material={materials['Material.001']} position={[-0.495, 194.248, -61.822]} rotation={[Math.PI / 2, 0.031, -Math.PI / 2]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cylinder035_Material001_0.geometry} material={materials['Material.001']} position={[-0.495, 209.207, -61.822]} rotation={[Math.PI / 2, -0.063, -Math.PI / 2]} scale={[0.268, 0.505, 0.268]} />
      <mesh geometry={nodes.Cube076_Material005_0.geometry} material={materials['Material.005']} position={[106.725, 307.13, 27.224]} rotation={[2.238, 0, -Math.PI / 2]} scale={[1.361, 1, 0.578]} />
      <mesh geometry={nodes.Cube077_Material005_0.geometry} material={materials['Material.005']} position={[129.642, 296.867, 21.627]} rotation={[2.487, -0.27, -1.525]} scale={[1.361, 1, 0.578]} />
      <mesh geometry={nodes.Cylinder036_Material006_0.geometry} material={materials['Material.006']} position={[161.15, 340.8, 0.28]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder037_Material006_0.geometry} material={materials['Material.006']} position={[289.123, 302.049, 0.28]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.76, 1.266, 0.76]} />
      <mesh geometry={nodes.Torus_Material002_0.geometry} material={materials['Material.002']} position={[161.15, 340.8, 9.068]} rotation={[Math.PI / 2, 0, 0]} scale={[0.883, 1.042, 0.883]} />
      <mesh geometry={nodes.Torus001_Material002_0.geometry} material={materials['Material.002']} position={[161.15, 340.8, 11.237]} rotation={[Math.PI / 2, 0, 0]} scale={0.957} />
      <mesh geometry={nodes.Torus002_Material002_0.geometry} material={materials['Material.002']} position={[289.357, 302.058, 10.688]} rotation={[Math.PI / 2, 0, 0]} scale={[0.639, 1.042, 0.639]} />
      <mesh geometry={nodes.Torus003_Material002_0.geometry} material={materials['Material.002']} position={[289.357, 302.058, 12.858]} rotation={[Math.PI / 2, 0, 0]} scale={[0.693, 0.957, 0.693]} />
      <mesh geometry={nodes.Torus004_Material002_0.geometry} material={materials['Material.002']} position={[183.298, 161.102, -72.444]} rotation={[-Math.PI, 0, 0]} scale={[2.548, 1.48, 2.548]} />
      <mesh geometry={nodes.Torus005_Material002_0.geometry} material={materials['Material.002']} position={[183.298, 161.102, 109.053]} rotation={[-Math.PI, 0, 0]} scale={[2.548, 1.48, 2.548]} />
      <mesh geometry={nodes.NurbsPath_Material002_0.geometry} material={materials['Material.002']} position={[161.15, 340.8, 10.085]} />
      <mesh geometry={nodes.Cylinder038_Material003_0.geometry} material={materials['Material.003']} position={[182.385, 120.71, 79.779]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder039_Material003_0.geometry} material={materials['Material.003']} position={[84.63, 120.71, 79.779]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder040_Material003_0.geometry} material={materials['Material.003']} position={[-16.791, 120.71, 79.779]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder041_Material003_0.geometry} material={materials['Material.003']} position={[182.385, 136.348, 79.352]} rotation={[2.062, 0, 0]} scale={0.923} />
      <mesh geometry={nodes.Cylinder042_Material003_0.geometry} material={materials['Material.003']} position={[132.974, 120.71, 109.978]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 1.798, 1]} />
      <mesh geometry={nodes.Cylinder043_Material003_0.geometry} material={materials['Material.003']} position={[34.995, 120.71, 109.978]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 1.798, 1]} />
      <mesh geometry={nodes.Cylinder044_Material003_0.geometry} material={materials['Material.003']} position={[34.995, 134.951, 109.978]} rotation={[Math.PI / 2, -0.215, -Math.PI / 2]} scale={[1, 1.798, 1]} />
      <mesh geometry={nodes.Cylinder045_Material003_0.geometry} material={materials['Material.003']} position={[190.761, 156.682, 112.087]} rotation={[Math.PI / 2, 0, 0]} scale={0.875} />
      <mesh geometry={nodes.NurbsPath001_Material002_0.geometry} material={materials['Material.002']} position={[183.298, 161.102, 216.053]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Torus006_Material002_0.geometry} material={materials['Material.002']} position={[95.322, 119.743, 250.171]} rotation={[-Math.PI, 0, 0]} scale={[2.048, 1.48, 2.048]} />
      <mesh geometry={nodes.Torus007_Material002_0.geometry} material={materials['Material.002']} position={[95.322, 122.278, 250.171]} rotation={[-Math.PI, 0, 0]} scale={[2.127, 1.644, 2.127]} />
      <mesh geometry={nodes.Torus008_Material002_0.geometry} material={materials['Material.002']} position={[-63.28, 118.736, 250.171]} rotation={[-Math.PI, 0, 0]} scale={[2.048, 1.48, 2.048]} />
      <mesh geometry={nodes.Torus009_Material002_0.geometry} material={materials['Material.002']} position={[-63.28, 121.27, 250.171]} rotation={[-Math.PI, 0, 0]} scale={[2.127, 1.644, 2.127]} />
      <mesh geometry={nodes.Torus010_Material001_0.geometry} material={materials['Material.001']} position={[-78.402, 156.901, 142.122]} rotation={[Math.PI / 4, 0, -Math.PI / 2]} scale={0.707} />
      <mesh geometry={nodes.Cylinder046_Material006_0.geometry} material={materials['Material.006']} position={[-78.402, 162.018, 140.057]} rotation={[Math.PI / 2, 0, 0]} scale={1.069} />
      <mesh geometry={nodes.Cylinder047_Material006_0.geometry} material={materials['Material.006']} position={[-78.402, 151.846, 140.057]} rotation={[Math.PI / 2, 0, 0]} scale={1.069} />
      <mesh geometry={nodes.Torus011_Material002_0.geometry} material={materials['Material.002']} position={[84.212, 127.767, 108.982]} rotation={[-Math.PI, 0, 0.149]} scale={[1.766, 1.277, 1.766]} />
      <mesh geometry={nodes.Torus012_Material002_0.geometry} material={materials['Material.002']} position={[84.212, 130.301, 108.982]} rotation={[-Math.PI, 0, 0.149]} scale={[1.834, 1.418, 1.834]} />
      <mesh geometry={nodes.Torus013_Material002_0.geometry} material={materials['Material.002']} position={[84.212, 123.392, 108.982]} rotation={[-2.742, -0.092, -0.065]} scale={[1.691, 1.222, 1.691]} />
      <mesh geometry={nodes.Torus014_Material002_0.geometry} material={materials['Material.002']} position={[84.212, 117.462, 108.982]} rotation={[2.963, 0, 0.228]} scale={[1.766, 1.277, 1.766]} />
      <mesh geometry={nodes.Torus015_Material002_0.geometry} material={materials['Material.002']} position={[-63.28, 98.658, 250.171]} rotation={[-Math.PI, 0, -0.085]} scale={[1.736, 1.254, 1.736]} />
      <mesh geometry={nodes.Torus016_Material002_0.geometry} material={materials['Material.002']} position={[-63.28, 101.192, 250.171]} rotation={[-Math.PI, 0, -0.085]} scale={[1.802, 1.393, 1.802]} />
      <mesh geometry={nodes.Torus017_Material002_0.geometry} material={materials['Material.002']} position={[-63.28, 94.599, 250.171]} rotation={[-Math.PI, 0, 0.308]} scale={[1.736, 1.254, 1.736]} />
      <mesh geometry={nodes.Torus018_Material002_0.geometry} material={materials['Material.002']} position={[-78.694, 156.56, 148.12]} rotation={[0.254, 0, 0]} scale={[0.596, 1.221, 0.596]} />
      <mesh geometry={nodes.Torus019_Material002_0.geometry} material={materials['Material.002']} position={[183.082, 120.818, 58.883]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.702, 1.069, 0.702]} />
      <mesh geometry={nodes.Torus020_Material002_0.geometry} material={materials['Material.002']} position={[183.082, 120.81, 61.103]} rotation={[-1.393, 0, 0]} scale={[0.687, 0.993, 0.633]} />
      <mesh geometry={nodes.Torus021_Material002_0.geometry} material={materials['Material.002']} position={[182.617, 120.544, 63.046]} rotation={[-1.517, 0, 0]} scale={[0.687, 0.993, 0.633]} />
      <mesh geometry={nodes.Torus022_Material002_0.geometry} material={materials['Material.002']} position={[183.1, 120.596, 94.39]} rotation={[-1.629, 0, 0]} scale={[0.739, 1.069, 0.682]} />
      <mesh geometry={nodes.Torus023_Material002_0.geometry} material={materials['Material.002']} position={[182.6, 120.808, 96.49]} rotation={[-1.753, 0, 0]} scale={[0.739, 1.069, 0.682]} />
      <mesh geometry={nodes.NurbsPath002_Material002_0.geometry} material={materials['Material.002']} position={[-78.402, 155.802, 227.318]} rotation={[0, Math.PI / 2, 0]} scale={0.719} />
      <mesh geometry={nodes.Torus024_Material001_0.geometry} material={materials['Material.001']} position={[283.245, 212.412, 15.484]} rotation={[Math.PI / 2, 0, -0.586]} />
      <mesh geometry={nodes.Torus025_Material002_0.geometry} material={materials['Material.002']} position={[287.483, 228.284, 12.948]} rotation={[-2.988, 0, 0]} scale={[0.636, 1.037, 0.636]} />
      <mesh geometry={nodes.Torus026_Material002_0.geometry} material={materials['Material.002']} position={[287.483, 226.397, 12.933]} rotation={[-2.988, 0, 0]} scale={[0.689, 0.952, 0.689]} />
      <mesh geometry={nodes.Cube078_Material005_0.geometry} material={materials['Material.005']} position={[-123.111, 251.133, 33.741]} rotation={[0, -0.822, 0]} />
      <mesh geometry={nodes.Cube079_Material010_0.geometry} material={materials['Material.010']} position={[-125.977, 273.284, 34.943]} rotation={[0, -0.822, 0]} />
      <mesh geometry={nodes.Cube080_Material005_0.geometry} material={materials['Material.005']} position={[-121.228, 259.229, -34.859]} rotation={[0.675, 0.635, -0.443]} />
      <mesh geometry={nodes.Cube081_Material009_0.geometry} material={materials['Material.009']} position={[-112.511, 284.026, -30.109]} rotation={[0.731, 0.62, -0.48]} scale={1.349} />
      <mesh geometry={nodes.Plane001_Material016_0.geometry} material={materials['Material.016']} position={[266.504, 280.4, -1.026]} rotation={[Math.PI / 2, 0, 0]} scale={[0.243, 0.209, 0.209]} />
      <mesh geometry={nodes.Plane002_Material016_0.geometry} material={materials['Material.016']} position={[231.295, 287.067, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.148, 0.127, 0.127]} />
      <mesh geometry={nodes.Plane003_Material016_0.geometry} material={materials['Material.016']} position={[205.804, 289.566, -0.802]} rotation={[Math.PI / 2, 0, 0]} scale={[0.148, 0.127, 0.084]} />
      <mesh geometry={nodes.Plane004_Material004_0.geometry} material={materials['Material.004']} position={[21.877, 88.105, 67.843]} scale={2.669} />
      <mesh geometry={nodes.Cube082_Material006_0.geometry} material={materials['Material.006']} position={[0, 201.51, 0]} />
      <mesh geometry={nodes.Cube083_Material009_0.geometry} material={materials['Material.009']} position={[12.501, 230.047, 2.828]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.065, 3.129, 1.867]} />
      <mesh geometry={nodes.Cube084_Material008_0.geometry} material={materials['Material.008']} position={[-12.115, 229.268, 107.385]} rotation={[0.31, 0, 0]} scale={[0.391, 1, 0.391]} />
      <mesh geometry={nodes.Cube085_Material005_0.geometry} material={materials['Material.005']} position={[-11.76, 229.525, 106.118]} rotation={[0.31, 0, 0]} scale={[0.391, 1, 0.391]} />
      <mesh geometry={nodes.Cube086_Material009_0.geometry} material={materials['Material.009']} position={[-12.115, 229.268, 107.385]} rotation={[0.31, 0, 0]} scale={[0.391, 1, 0.391]} />
      <mesh geometry={nodes.Cylinder048_Material014_0.geometry} material={materials['Material.014']} position={[135.789, 86.532, 239.334]} rotation={[0.072, -0.111, -0.107]} scale={0.556} />
      <mesh geometry={nodes.Cylinder049_Material014_0.geometry} material={materials['Material.014']} position={[118.811, 84.184, 128.637]} rotation={[0.067, -0.587, 0.032]} />
      <mesh geometry={nodes.Cylinder050_Material014_0.geometry} material={materials['Material.014']} position={[142.16, 84.431, 130.568]} rotation={[0.127, -0.846, 0.059]} scale={0.549} />
      <mesh geometry={nodes.Cylinder051_Material014_0.geometry} material={materials['Material.014']} position={[109.915, 88.794, 242.137]} rotation={[-Math.PI, 1.477, -Math.PI]} scale={0.682} />
      <mesh geometry={nodes.Cylinder052_Material014_0.geometry} material={materials['Material.014']} position={[209.727, 85.535, 226.108]} rotation={[0.224, -0.722, 0.127]} />
      <mesh geometry={nodes.Cylinder053_Material014_0.geometry} material={materials['Material.014']} position={[179.276, 82.158, 257.116]} rotation={[0.142, 0.6, -0.249]} scale={0.539} />
      <mesh geometry={nodes.Cylinder054_Material014_0.geometry} material={materials['Material.014']} position={[204.104, 84.144, 254.787]} rotation={[0.056, -0.767, 0.279]} scale={0.735} />
      <mesh geometry={nodes.Cylinder055_Material014_0.geometry} material={materials['Material.014']} position={[-207.044, 85.535, 236.414]} rotation={[0.113, -0.799, 0.067]} />
    </group>
  )
}

useGLTF.preload('/xyz_homework_detailed_draft_fishermans_house.glb')
