/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/casa_obj.glb 
Author: Dudehtm (https://sketchfab.com/Dude_HTM)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/casa-obj-7feda36112164313abc52595d07dd549
Title: Casa OBJ
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/casa_obj.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.LAMPARA} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.VIDRIO} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Verde} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.agua} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.pared} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.CESPED} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.CESPED} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.CESPED} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.CESPED} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.CESPED} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.CESPED} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.ROCA} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.ROCA} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.madera} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.teja1} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.teja2} />
      </group>
    </group>
  )
}

useGLTF.preload('/casa_obj.glb')
